

# This file was *autogenerated* from the file audit/verify_e8_orthogonality.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7)
from sage.all import *
L = RootSystem(['E', _sage_const_8 ]).root_lattice()
roots = L.simple_roots()
# Bourbaki diagram: 1-2-3-4-5-6-7, 5-8
# We want independent sets (orthogonal roots)
# Set A: {1, 3, 6, 8}
# Set B: {2, 4, 7}
# Let's check my sets from task5_1: {1, 4, 6, 8} and {2, 3, 5, 7}?
set_A = [_sage_const_1 , _sage_const_4 , _sage_const_6 , _sage_const_8 ]
set_B = [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 ]
print(f"Checking Set A: {set_A}")
for i in set_A:
    for j in set_A:
        if i < j:
            pair = roots[i].inner_product(roots[j])
            print(f"  ({i}, {j}) pairing = {pair}")
print(f"Checking Set B: {set_B}")
for i in set_B:
    for j in set_B:
        if i < j:
            pair = roots[i].inner_product(roots[j])
            print(f"  ({i}, {j}) pairing = {pair}")

