

# This file was *autogenerated* from the file audit/verify_e8_orthogonality_v3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7)
from sage.all import *
W = RootSystem(['E', _sage_const_8 ]).weight_lattice()
roots = W.simple_roots()
# In E8, simple roots have norm 2. Orthogonal roots have scalar product 0.
set_A = [_sage_const_1 , _sage_const_4 , _sage_const_6 , _sage_const_8 ]
set_B = [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 ]
def check_set(name, indices):
    print(f"Checking {name}: {indices}")
    for i in indices:
        for j in indices:
            if i < j:
                # Use scalar product in the weight lattice
                val = roots[i].inner_product(roots[j])
                print(f"  ({i}, {j}) pairing = {val}")
check_set("Set A", set_A)
check_set("Set B", set_B)

