

# This file was *autogenerated* from the file audit/verify_e8_orthogonality_v4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6)
from sage.all import *
A = CartanMatrix(['E', _sage_const_8 ])
set_A = [_sage_const_0 , _sage_const_3 , _sage_const_5 , _sage_const_7 ] # 0-indexed for CartanMatrix
set_B = [_sage_const_1 , _sage_const_2 , _sage_const_4 , _sage_const_6 ]
def check_set(name, indices):
    print(f"Checking {name}: {indices}")
    for i in indices:
        for j in indices:
            if i < j:
                val = A[i, j]
                print(f"  ({i+_sage_const_1 }, {j+_sage_const_1 }) pairing = {val}")
check_set("Set A", [i+_sage_const_1  for i in set_A])
check_set("Set B", [i+_sage_const_1  for i in set_B])

