r"""One-object subcategory for callable-backed enumerated sets."""

from __future__ import annotations

from collections.abc import Iterator
from typing import TYPE_CHECKING, Any, final, override

from sage.categories.category_singleton import Category_singleton
from sage.misc.abstract_method import abstract_method

if TYPE_CHECKING:
    from ...types import Cardinality, SetElement


from ...cat import Category
from .. import Sets


class _EnumeratedSetsFromIterator(Category_singleton):
    r"""Enumerated set generated by a callable returning a fresh iterator.

    Constructor target:
    ``Sets().Constructors().EnumeratedSetFromIterator(iterator_factory)``
    refines Sage's callable-backed enumerated-set parent here.
    """

    @override
    @final
    def super_categories(self) -> list[Category]:
        return [Sets().Countable()]

    class ParentMethods:
        @override
        @abstract_method
        def __contains__(self, x: Any) -> bool: ...

        @override
        @abstract_method
        def __iter__(self) -> Iterator[SetElement]: ...

        @override
        @abstract_method
        def cardinality(self) -> Cardinality: ...

        @override
        @abstract_method
        def an_element(self) -> SetElement: ...

        @override
        @abstract_method
        def _element_constructor_(self, el: SetElement) -> SetElement: ...

        @abstract_method
        def clear_cache(self) -> None:
            r"""Clear the iterator cache of this callable-backed enumerated set."""
            ...

    class ElementMethods: ...

    class MorphismMethods: ...
