r"""One-object subcategory for callable-backed enumerated sets."""

from __future__ import annotations

from collections.abc import Iterator
from typing import TYPE_CHECKING, Any, final, override

from sage.categories.category_singleton import Category_singleton
from sage.categories.finite_enumerated_sets import (
    FiniteEnumeratedSets as SageFiniteEnumeratedSets,
)
from sage.categories.infinite_enumerated_sets import (
    InfiniteEnumeratedSets as SageInfiniteEnumeratedSets,
)
from sage.rings.infinity import infinity

if TYPE_CHECKING:
    from ...types import Cardinality, SetElement


from ...cat import Category
from .. import Sets


class _EnumeratedSetsFromIterator(Category_singleton):
    r"""Enumerated set generated by a callable returning a fresh iterator.

    Constructor target:
    ``Sets().Constructors().EnumeratedSetFromIterator(iterator_factory)``
    refines Sage's callable-backed enumerated-set parent here.
    """

    @override
    @final
    def super_categories(self) -> list[Category]:
        return [Sets().Countable()]

    class ParentMethods:
        @override
        @final
        def is_finite(self) -> bool:
            if self.category().is_subcategory(SageFiniteEnumeratedSets()):
                return True
            if self.category().is_subcategory(SageInfiniteEnumeratedSets()):
                return False
            raise NotImplementedError("iterator-backed set finiteness requires finite or infinite category evidence")

        @override
        @final
        def __contains__(self, x: Any) -> bool:
            return any(x == y for y in self)

        @override
        @final
        def __iter__(self) -> Iterator[SetElement]:
            if hasattr(self, "_cache"):
                return iter(self._cache)
            return iter(
                self._func(
                    *getattr(self, "_args", ()),
                    **getattr(self, "_kwds", {}),
                )
            )

        @override
        @final
        def cardinality(self) -> Cardinality:
            if self.category().is_subcategory(SageInfiniteEnumeratedSets()):
                return infinity
            if not self.category().is_subcategory(SageFiniteEnumeratedSets()):
                raise NotImplementedError("iterator-backed cardinality requires finite or infinite category evidence")
            return SageFiniteEnumeratedSets.ParentMethods.cardinality(self)

        @override
        @final
        def an_element(self) -> SetElement:
            return self._an_element_()

        @override
        @final
        def _element_constructor_(self, el: SetElement) -> SetElement:
            if el in self:
                return el
            raise ValueError(f"{el} not in {self}")

        @final
        def clear_cache(self) -> None:
            r"""Clear the iterator cache of this callable-backed enumerated set."""
            if hasattr(self, "_cache"):
                from sage.misc.lazy_list import lazy_list

                self._cache = lazy_list(
                    iter(
                        self._func(
                            *getattr(self, "_args", ()),
                            **getattr(self, "_kwds", {}),
                        )
                    )
                )

    class ElementMethods: ...

    class MorphismMethods: ...
