r"""One-object subcategory for Sage recursively enumerated sets."""

from __future__ import annotations

from abc import abstractmethod
from collections.abc import Callable, Iterator
from typing import TYPE_CHECKING, Any, cast, final, override

from sage.categories.category_singleton import Category_singleton
from sage.categories.finite_enumerated_sets import (
    FiniteEnumeratedSets as SageFiniteEnumeratedSets,
)
from sage.categories.infinite_enumerated_sets import (
    InfiniteEnumeratedSets as SageInfiniteEnumeratedSets,
)
from sage.sets.recursively_enumerated_set import (
    RecursivelyEnumeratedSet_forest as SageRecursivelyEnumeratedSetForest,
)
from sage.sets.recursively_enumerated_set import (
    RecursivelyEnumeratedSet_generic as SageRecursivelyEnumeratedSetGeneric,
)

if TYPE_CHECKING:
    from ...types import (
        Cardinality,
        CategoryElement,
        DiGraph,
        InfinityElement,
        Integer,
        Set,
        SetElement,
    )


from ...cat import Category
from .. import Sets


class _RecursivelyEnumeratedSets(Category_singleton):
    r"""Sets generated from seeds and successor functions.

    Constructor target:
    ``Sets().Constructors().RecursivelyEnumeratedSet(...)`` refines Sage's
    recursive-enumeration parent here.
    """

    @override
    @final
    def super_categories(self) -> list[Category]:
        return [Sets().Countable()]

    class ParentMethods:
        @override
        @abstractmethod
        def __len__(self) -> Integer: ...

        @override
        @abstractmethod
        def __iter__(self) -> Iterator[SetElement]: ...

        @override
        @abstractmethod
        def __contains__(self, elt: Any) -> bool: ...

        @override
        @final
        def is_finite(self) -> bool:
            if self.category().is_subcategory(SageFiniteEnumeratedSets()):
                return True
            if self.category().is_subcategory(SageInfiniteEnumeratedSets()):
                return False
            if isinstance(self, SageRecursivelyEnumeratedSetGeneric):
                from sage.rings.infinity import infinity

                return cast(
                    bool,
                    self._max_depth != float("inf") and self._max_depth != infinity,
                )
            raise NotImplementedError(
                "recursive set finiteness requires category or depth evidence"
            )

        @override
        @final
        def cardinality(self) -> Cardinality:
            if self.category().is_subcategory(SageFiniteEnumeratedSets()):
                return SageFiniteEnumeratedSets.ParentMethods.cardinality(self)
            if self.category().is_subcategory(SageInfiniteEnumeratedSets()):
                from sage.rings.infinity import infinity

                return infinity
            raise NotImplementedError(
                "recursive cardinality requires finite or infinite category evidence"
            )

        @abstractmethod
        def graded_component_iterator(self) -> Iterator[Set]:
            r"""Return the iterator over recursive-enumeration graded components."""
            ...

        @abstractmethod
        def elements_of_depth_iterator(self, depth: Integer) -> Iterator[SetElement]:
            r"""Return the elements reached at recursive depth ``depth``."""
            ...

        @abstractmethod
        def breadth_first_search_iterator(
            self,
            max_depth: Integer | InfinityElement | None = None,
        ) -> Iterator[SetElement]:
            r"""Return the breadth-first traversal of this recursive enumeration."""
            ...

        @abstractmethod
        def naive_search_iterator(self) -> Iterator[SetElement]:
            r"""Return Sage's naive traversal of this recursive enumeration."""
            ...

        @abstractmethod
        def depth_first_search_iterator(self) -> Iterator[SetElement]:
            r"""Return the depth-first traversal of this recursive enumeration."""
            ...

        @abstractmethod
        def to_digraph(
            self,
            max_depth: Integer | InfinityElement | None = None,
            loops: bool = True,
            multiedges: bool = True,
        ) -> DiGraph:
            r"""Return the graph generated by the recursive successor relation."""
            del loops, multiedges
            ...

        @final
        def roots(self) -> Set:
            r"""Return the seed set of this recursive forest."""
            if isinstance(self, SageRecursivelyEnumeratedSetForest):
                return cast(Set, SageRecursivelyEnumeratedSetForest.roots(self))
            if isinstance(self, SageRecursivelyEnumeratedSetGeneric):
                return cast(Set, self.seeds())
            raise NotImplementedError(
                "recursive roots require generic seeds or forest roots"
            )

        @final
        def children(self, x: SetElement) -> Set:
            r"""Return the recursive successors of ``x``."""
            if isinstance(self, SageRecursivelyEnumeratedSetGeneric):
                return cast(Set, self.successors(x))
            raise NotImplementedError(
                "recursive children require a generic Sage successor function"
            )

        @final
        def map_reduce(
            self,
            map_function: Callable[[SetElement], CategoryElement] | None = None,
            reduce_function: Callable[
                [CategoryElement, CategoryElement], CategoryElement
            ]
            | None = None,
            reduce_init: CategoryElement | Integer | None = None,
        ) -> CategoryElement | Integer:
            r"""Run Sage's recursive map-reduce traversal."""
            if isinstance(self, SageRecursivelyEnumeratedSetForest):
                return SageRecursivelyEnumeratedSetForest.map_reduce(
                    self,
                    map_function=map_function,
                    reduce_function=reduce_function,
                    reduce_init=reduce_init,
                )
            raise NotImplementedError(
                "recursive map-reduce is defined for forest-structured recursive sets"
            )

    class ElementMethods: ...
