r"""Finite meet-semilattice poset subcategory."""

from __future__ import annotations

from typing import TYPE_CHECKING, cast, final, override

from abc import abstractmethod

from ...cat import Category
from ...cat import CategoryWithAxiom_singleton as CategoryWithAxiom
from .meet_semilattice import _MeetSemilatticePosets

if TYPE_CHECKING:
    from ...types import FiniteMeetSemilatticePoset, Matrix, PosetElement


class _FiniteMeetSemilatticePosets(CategoryWithAxiom):
    r"""Finite posets in which every pair has a meet.

    Canonical chain: ``Posets().MeetSemilattice().Finite()``.
    """

    _base_category_class_and_axiom = (_MeetSemilatticePosets, "Finite")

    @override
    @final
    def super_categories(self) -> list[Category]:
        r"""Return meet-semilattice and finite-poset supercategories."""
        from .. import Posets

        return [_MeetSemilatticePosets(), Posets().Finite()]

    class ParentMethods:
        @abstractmethod
        def atoms(self) -> list[PosetElement]:
            r"""Return the elements covering the bottom element."""
            ...

        @abstractmethod
        def meet_matrix(self) -> Matrix:
            r"""Return the matrix of pairwise meets."""
            ...

        @abstractmethod
        def pseudocomplement(self, element: PosetElement) -> PosetElement:
            r"""Return the meet-pseudocomplement of ``element``."""
            ...

        @final
        def submeetsemilattice(
            self, elements: list[PosetElement]
        ) -> FiniteMeetSemilatticePoset:
            r"""Return the meet-subsemilattice generated by ``elements``."""
            from sage.combinat.posets.lattices import (
                MeetSemilattice as SageMeetSemilattice,
            )

            from ....utils import refine_category
            from .. import Posets

            generators = set(elements)
            closure: set[PosetElement] = set()
            while generators:
                generator = generators.pop()
                if generator in closure:
                    continue
                for element in closure:
                    generators.add(self.meet(element, generator))
                closure.add(generator)

            raw = SageMeetSemilattice(self.subposet(closure))
            return cast(
                FiniteMeetSemilatticePoset,
                refine_category(raw, [Posets().MeetSemilattice().Finite()]),
            )

    class ElementMethods: ...

    class MorphismMethods: ...
