r"""Finite join-semilattice poset subcategory."""

from __future__ import annotations

from typing import TYPE_CHECKING, final, override

from sage.misc.abstract_method import abstract_method

from ...cat import Category
from ...cat import CategoryWithAxiom_singleton as CategoryWithAxiom
from .join_semilattice import _JoinSemilatticePosets

if TYPE_CHECKING:
    from ...types import FiniteJoinSemilatticePoset, Matrix, PosetElement


class _FiniteJoinSemilatticePosets(CategoryWithAxiom):
    r"""Finite posets in which every pair has a join.

    Canonical chain: ``Posets().JoinSemilattice().Finite()``.
    """

    _base_category_class_and_axiom = (_JoinSemilatticePosets, "Finite")

    @override
    @final
    def super_categories(self) -> list[Category]:
        r"""Return join-semilattice and finite-poset supercategories."""
        from .. import Posets

        return [_JoinSemilatticePosets(), Posets().Finite()]

    class ParentMethods:
        @abstract_method
        def coatoms(self) -> list[PosetElement]:
            r"""Return the elements covered by the top element."""
            ...

        @abstract_method
        def join_matrix(self) -> Matrix:
            r"""Return the matrix of pairwise joins."""
            ...

        @final
        def subjoinsemilattice(
            self, elements: list[PosetElement]
        ) -> FiniteJoinSemilatticePoset:
            r"""Return the join-subsemilattice generated by ``elements``."""
            from sage.combinat.posets.lattices import (
                JoinSemilattice as SageJoinSemilattice,
            )

            from ....utils import refine_category
            from .. import Posets

            generators = set(elements)
            closure: set[PosetElement] = set()
            while generators:
                generator = generators.pop()
                if generator in closure:
                    continue
                for element in closure:
                    generators.add(self.join(element, generator))
                closure.add(generator)

            raw = SageJoinSemilattice(self.subposet(closure))
            return refine_category(raw, [Posets().JoinSemilattice().Finite()])

    class ElementMethods: ...

    class MorphismMethods: ...
