r"""Order-theoretic poset category surface.

Subcategory hierarchy::

    Posets()
    |-- Finite()
    |-- MeetSemilattice()
    |   `-- Finite()
    |-- JoinSemilattice()
    |   `-- Finite()
    |-- Lattice()
    |   `-- Finite()
    `-- HomCategory()
        |-- EndCategory()
        `-- AutCategory()

The root category specifies sets equipped with a partial order. Lattice posets
are order-theoretic meet/join lattices, not module lattices.
"""

from __future__ import annotations

from abc import abstractmethod
from collections.abc import Callable, Iterable, Sequence
from typing import (
    TypeAlias,
    TYPE_CHECKING,
    Any,
    final,
    overload,
    override,
)

from sage.categories.posets import Posets as SagePosets
from sage.misc.lazy_import import LazyImport

from ..cat import Category
from ..sets import Sets
from ..utils import refine_category
from .homsets import (
    PosetAutCategory,
    PosetEndCategory,
    PosetHomCategory,
    _OrderPreservingMaps,
)

if TYPE_CHECKING:
    from ..spec_core import ConstructorRegistry
    from ..types import (
        DiGraph,
        FiniteJoinSemilatticePoset,
        FiniteLatticePoset,
        FiniteMeetSemilatticePoset,
        Poset as _Poset,
        PosetElement,
        PosetSubset,
        SageFinitePoset,
    )

if TYPE_CHECKING:
    @overload
    def abstract_method[_MethodT: Callable[..., object]](
        function: _MethodT, /
    ) -> _MethodT: ...

    @overload
    def abstract_method[_MethodT: Callable[..., object]](
        *, optional: bool = False
    ) -> Callable[[_MethodT], _MethodT]: ...

    def abstract_method[_MethodT: Callable[..., object]](
        function: _MethodT | None = None, *, optional: bool = False
    ) -> _MethodT | Callable[[_MethodT], _MethodT]: ...

else:
    from sage.misc.abstract_method import abstract_method


def _poset_constructor_identity_key(element: PosetElement) -> PosetElement:
    return element


def _finite_poset_cover_data(
    poset: SageFinitePoset,
) -> tuple[list[PosetElement], list[tuple[PosetElement, PosetElement]]]:
    return (
        list(poset),
        [tuple(relation) for relation in poset.cover_relations()],
    )


class _PosetParentMethods:
    r"""Methods on partially ordered sets."""

    @override
    @abstractmethod
    def le(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x <= y`` in this poset."""
        ...

    @override
    @final
    def lt(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x < y`` in this poset."""
        return self.le(x, y) and x != y

    @override
    @final
    def ge(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x >= y`` in this poset."""
        return self.le(y, x)

    @override
    @final
    def gt(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x > y`` in this poset."""
        return self.lt(y, x)

    @override
    @abstractmethod
    @abstract_method(optional=True)
    def upper_covers(self, x: PosetElement) -> list[PosetElement]:
        r"""Return the elements covering ``x`` from above."""
        ...

    @override
    @abstractmethod
    @abstract_method(optional=True)
    def lower_covers(self, x: PosetElement) -> list[PosetElement]:
        r"""Return the elements covered by ``x``."""
        ...

    @override
    @abstractmethod
    @abstract_method(optional=True)
    def order_ideal(self, elements: Iterable[PosetElement]) -> PosetSubset:
        r"""Return the lower set generated by ``elements``."""
        ...

    @override
    @abstractmethod
    @abstract_method(optional=True)
    def order_filter(self, elements: Iterable[PosetElement]) -> PosetSubset:
        r"""Return the upper set generated by ``elements``."""
        ...

    @override
    @final
    def directed_subset(
        self, elements: Iterable[PosetElement], direction: str
    ) -> PosetSubset:
        r"""Return the order ideal or order filter generated by ``elements``."""
        return SagePosets.ParentMethods.directed_subset(self, elements, direction)

    @override
    @final
    def principal_order_ideal(self, x: PosetElement) -> PosetSubset:
        r"""Return the principal lower set generated by ``x``."""
        return SagePosets.ParentMethods.principal_order_ideal(self, x)

    @override
    @final
    def principal_order_filter(self, x: PosetElement) -> PosetSubset:
        r"""Return the principal upper set generated by ``x``."""
        return SagePosets.ParentMethods.principal_order_filter(self, x)

    @override
    @final
    def order_ideal_toggle(self, ideal: PosetSubset, x: PosetElement) -> PosetSubset:
        r"""Toggle ``x`` in the distributive lattice of order ideals."""
        return SagePosets.ParentMethods.order_ideal_toggle(self, ideal, x)

    @override
    @final
    def order_ideal_toggles(
        self,
        ideal: PosetSubset,
        elements: Iterable[PosetElement],
    ) -> PosetSubset:
        r"""Apply order-ideal toggles in sequence."""
        return SagePosets.ParentMethods.order_ideal_toggles(self, ideal, elements)

    @override
    @final
    def is_order_ideal(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an order ideal."""
        return SagePosets.ParentMethods.is_order_ideal(self, subset)

    @override
    @final
    def is_order_filter(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an order filter."""
        return SagePosets.ParentMethods.is_order_filter(self, subset)

    @override
    @final
    def is_chain_of_poset(
        self, subset: Iterable[PosetElement], ordered: bool = False
    ) -> bool:
        r"""Return whether ``subset`` is a chain."""
        return SagePosets.ParentMethods.is_chain_of_poset(
            self, subset, ordered=ordered
        )

    @override
    @final
    def is_antichain_of_poset(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an antichain."""
        return SagePosets.ParentMethods.is_antichain_of_poset(self, subset)


class _PosetElementMethods:
    r"""Methods on elements of non-facade posets."""

    @abstractmethod
    def __le__(self, other: PosetElement) -> bool:
        r"""Return whether this element is less than or equal to ``other``."""
        ...

    @abstractmethod
    def __lt__(self, other: PosetElement) -> bool:
        r"""Return whether this element is strictly less than ``other``."""
        ...

    @abstractmethod
    def __ge__(self, other: PosetElement) -> bool:
        r"""Return whether this element is greater than or equal to ``other``."""
        ...

    @abstractmethod
    def __gt__(self, other: PosetElement) -> bool:
        r"""Return whether this element is strictly greater than ``other``."""
        ...


class Posets(Category):
    r"""Category of sets equipped with a partial order.

    Canonical chain: ``Posets()``.
    """

    @final
    def _sage_super_categories(self) -> tuple[Category, ...]:
        return (SagePosets(),)

    @override
    @final
    def super_categories(self) -> list[Category]:
        r"""Return sets and Sage posets as supercategories."""
        return [Sets(), SagePosets()]

    class SubcategoryMethods:
        @final
        def Finite(self) -> Category:
            r"""Return the finite-poset subcategory."""
            return self._with_axiom("Finite")
        @final
        def MeetSemilattice(self) -> Category:
            r"""Return the meet-semilattice subcategory of posets."""
            from .subcategories.meet_semilattice import _MeetSemilatticePosets

            return _MeetSemilatticePosets()
        @final
        def JoinSemilattice(self) -> Category:
            r"""Return the join-semilattice subcategory of posets."""
            from .subcategories.join_semilattice import _JoinSemilatticePosets

            return _JoinSemilatticePosets()
        @final
        def Lattice(self) -> Category:
            r"""Return the order-theoretic lattice subcategory of posets."""
            from .subcategories.lattice import _LatticePosets

            return _LatticePosets()

    class _Constructors:
        r"""Poset constructors.

        The Hasse- and relation-digraph constructors are canonical graph
        adaptations of Sage's documented finite ``Poset(...)`` input cases.
        """

        @final
        def provenance(self) -> ConstructorRegistry:
            r"""Return typed provenance records for poset constructors."""
            from category_specs.spec_core import constructor_registry_for_category

            return constructor_registry_for_category(
                Posets(), owner_category="Posets()", id_prefix="posets"
            )

        @final
        def _raw_poset(
            self,
            data: Any,
            *,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            cover_relations: bool = False,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> SageFinitePoset:
            from sage.combinat.posets.posets import Poset as SagePoset

            return SagePoset(
                data,
                element_labels=element_labels,
                cover_relations=cover_relations,
                linear_extension=linear_extension,
                facade=facade,
                key=key,
            )

        @final
        def _refine_constructed_poset(
            self, poset: SageFinitePoset, category: Category
        ) -> _Poset:
            return refine_category(poset, category)

        @final
        def _refine_meet_semilattice(
            self, poset: SageFinitePoset
        ) -> FiniteMeetSemilatticePoset:
            from sage.combinat.posets.lattices import (
                MeetSemilattice as SageMeetSemilattice,
            )

            assert poset.is_meet_semilattice(), (
                "constructed poset is not a meet-semilattice"
            )
            return self._refine_constructed_poset(
                SageMeetSemilattice(
                    _finite_poset_cover_data(poset),
                    cover_relations=True,
                    check=False,
                    key=_poset_constructor_identity_key,
                ),
                Posets().MeetSemilattice().Finite(),
            )

        @final
        def _refine_join_semilattice(
            self, poset: SageFinitePoset
        ) -> FiniteJoinSemilatticePoset:
            from sage.combinat.posets.lattices import (
                JoinSemilattice as SageJoinSemilattice,
            )

            assert poset.is_join_semilattice(), (
                "constructed poset is not a join-semilattice"
            )
            return self._refine_constructed_poset(
                SageJoinSemilattice(
                    _finite_poset_cover_data(poset),
                    cover_relations=True,
                    check=False,
                    key=_poset_constructor_identity_key,
                ),
                Posets().JoinSemilattice().Finite(),
            )

        @final
        def _refine_lattice(self, poset: SageFinitePoset) -> FiniteLatticePoset:
            from sage.combinat.posets.lattices import LatticePoset as SageLatticePoset

            assert poset.is_meet_semilattice(), (
                "constructed poset is not a meet-semilattice"
            )
            assert poset.is_join_semilattice(), (
                "constructed poset is not a join-semilattice"
            )
            return self._refine_constructed_poset(
                SageLatticePoset(
                    _finite_poset_cover_data(poset),
                    cover_relations=True,
                    check=False,
                    key=_poset_constructor_identity_key,
                ),
                Posets().Lattice().Finite(),
            )

        @final
        def _raw_poset_from_named_input(
            self,
            *,
            hasse_digraph: DiGraph | None = None,
            relation_digraph: DiGraph | None = None,
            elements: Iterable[PosetElement] | None = None,
            relations: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            covers: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            order_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            cover_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]]
            | None = None,
            upper_covers: Sequence[Sequence[PosetElement]] | None = None,
            existing: _Poset | None = None,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> SageFinitePoset:
            relation_shape = elements is not None and relations is not None
            cover_shape = elements is not None and covers is not None
            order_predicate_shape = (
                elements is not None and order_predicate is not None
            )
            cover_predicate_shape = (
                elements is not None and cover_predicate is not None
            )
            selected_shapes = (
                hasse_digraph is not None,
                relation_digraph is not None,
                relation_shape,
                cover_shape,
                order_predicate_shape,
                cover_predicate_shape,
                upper_covers_dict is not None,
                upper_covers is not None,
                existing is not None,
            )
            assert sum(selected_shapes) == 1, (
                "constructor requires exactly one named Poset input shape"
            )

            if hasse_digraph is not None:
                return self._raw_poset(
                    hasse_digraph,
                    element_labels=element_labels,
                    cover_relations=True,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            if relation_digraph is not None:
                return self._raw_poset(
                    relation_digraph,
                    element_labels=element_labels,
                    cover_relations=False,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            if relation_shape:
                return self._raw_poset(
                    (elements, relations),
                    element_labels=element_labels,
                    cover_relations=False,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            if cover_shape:
                return self._raw_poset(
                    (elements, covers),
                    element_labels=element_labels,
                    cover_relations=True,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            if order_predicate_shape:
                return self._raw_poset(
                    (elements, order_predicate),
                    element_labels=element_labels,
                    cover_relations=False,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            if cover_predicate_shape:
                return self._raw_poset(
                    (elements, cover_predicate),
                    element_labels=element_labels,
                    cover_relations=True,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            if upper_covers_dict is not None:
                return self._raw_poset(
                    upper_covers_dict,
                    element_labels=element_labels,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            if upper_covers is not None:
                return self._raw_poset(
                    upper_covers,
                    element_labels=element_labels,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            assert existing is not None
            return self._raw_poset(existing)

        @overload
        def Poset(
            self,
            *,
            hasse_digraph: DiGraph,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset: ...

        @overload
        def Poset(
            self,
            *,
            relation_digraph: DiGraph,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset: ...

        @overload
        def Poset(
            self,
            *,
            elements: Iterable[PosetElement],
            relations: Iterable[tuple[PosetElement, PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset: ...

        @overload
        def Poset(
            self,
            *,
            elements: Iterable[PosetElement],
            covers: Iterable[tuple[PosetElement, PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset: ...

        @overload
        def Poset(
            self,
            *,
            elements: Iterable[PosetElement],
            order_predicate: Callable[[PosetElement, PosetElement], bool],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset: ...

        @overload
        def Poset(
            self,
            *,
            elements: Iterable[PosetElement],
            cover_predicate: Callable[[PosetElement, PosetElement], bool],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset: ...

        @overload
        def Poset(
            self,
            *,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset: ...

        @overload
        def Poset(
            self,
            *,
            upper_covers: Sequence[Sequence[PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset: ...

        @overload
        def Poset(
            self,
            *,
            existing: _Poset,
        ) -> _Poset: ...

        @final
        def Poset(
            self,
            *,
            hasse_digraph: DiGraph | None = None,
            relation_digraph: DiGraph | None = None,
            elements: Iterable[PosetElement] | None = None,
            relations: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            covers: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            order_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            cover_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]]
            | None = None,
            upper_covers: Sequence[Sequence[PosetElement]] | None = None,
            existing: _Poset | None = None,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> _Poset:
            r"""Return the finite poset determined by one named input shape."""
            return self._refine_constructed_poset(
                self._raw_poset_from_named_input(
                    hasse_digraph=hasse_digraph,
                    relation_digraph=relation_digraph,
                    elements=elements,
                    relations=relations,
                    covers=covers,
                    order_predicate=order_predicate,
                    cover_predicate=cover_predicate,
                    upper_covers_dict=upper_covers_dict,
                    upper_covers=upper_covers,
                    existing=existing,
                    element_labels=element_labels,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                ),
                Posets().Finite(),
            )

        @overload
        def MeetSemilattice(
            self,
            *,
            hasse_digraph: DiGraph,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset: ...

        @overload
        def MeetSemilattice(
            self,
            *,
            relation_digraph: DiGraph,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset: ...

        @overload
        def MeetSemilattice(
            self,
            *,
            elements: Iterable[PosetElement],
            relations: Iterable[tuple[PosetElement, PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset: ...

        @overload
        def MeetSemilattice(
            self,
            *,
            elements: Iterable[PosetElement],
            covers: Iterable[tuple[PosetElement, PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset: ...

        @overload
        def MeetSemilattice(
            self,
            *,
            elements: Iterable[PosetElement],
            order_predicate: Callable[[PosetElement, PosetElement], bool],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset: ...

        @overload
        def MeetSemilattice(
            self,
            *,
            elements: Iterable[PosetElement],
            cover_predicate: Callable[[PosetElement, PosetElement], bool],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset: ...

        @overload
        def MeetSemilattice(
            self,
            *,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset: ...

        @overload
        def MeetSemilattice(
            self,
            *,
            upper_covers: Sequence[Sequence[PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset: ...

        @overload
        def MeetSemilattice(
            self,
            *,
            existing: _Poset,
        ) -> FiniteMeetSemilatticePoset: ...

        @final
        def MeetSemilattice(
            self,
            *,
            hasse_digraph: DiGraph | None = None,
            relation_digraph: DiGraph | None = None,
            elements: Iterable[PosetElement] | None = None,
            relations: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            covers: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            order_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            cover_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]]
            | None = None,
            upper_covers: Sequence[Sequence[PosetElement]] | None = None,
            existing: _Poset | None = None,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteMeetSemilatticePoset:
            r"""Return the finite meet-semilattice from a named poset input."""
            return self._refine_meet_semilattice(
                self._raw_poset_from_named_input(
                    hasse_digraph=hasse_digraph,
                    relation_digraph=relation_digraph,
                    elements=elements,
                    relations=relations,
                    covers=covers,
                    order_predicate=order_predicate,
                    cover_predicate=cover_predicate,
                    upper_covers_dict=upper_covers_dict,
                    upper_covers=upper_covers,
                    existing=existing,
                    element_labels=element_labels,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            )

        @overload
        def JoinSemilattice(
            self,
            *,
            hasse_digraph: DiGraph,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset: ...

        @overload
        def JoinSemilattice(
            self,
            *,
            relation_digraph: DiGraph,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset: ...

        @overload
        def JoinSemilattice(
            self,
            *,
            elements: Iterable[PosetElement],
            relations: Iterable[tuple[PosetElement, PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset: ...

        @overload
        def JoinSemilattice(
            self,
            *,
            elements: Iterable[PosetElement],
            covers: Iterable[tuple[PosetElement, PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset: ...

        @overload
        def JoinSemilattice(
            self,
            *,
            elements: Iterable[PosetElement],
            order_predicate: Callable[[PosetElement, PosetElement], bool],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset: ...

        @overload
        def JoinSemilattice(
            self,
            *,
            elements: Iterable[PosetElement],
            cover_predicate: Callable[[PosetElement, PosetElement], bool],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset: ...

        @overload
        def JoinSemilattice(
            self,
            *,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset: ...

        @overload
        def JoinSemilattice(
            self,
            *,
            upper_covers: Sequence[Sequence[PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset: ...

        @overload
        def JoinSemilattice(
            self,
            *,
            existing: _Poset,
        ) -> FiniteJoinSemilatticePoset: ...

        @final
        def JoinSemilattice(
            self,
            *,
            hasse_digraph: DiGraph | None = None,
            relation_digraph: DiGraph | None = None,
            elements: Iterable[PosetElement] | None = None,
            relations: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            covers: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            order_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            cover_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]]
            | None = None,
            upper_covers: Sequence[Sequence[PosetElement]] | None = None,
            existing: _Poset | None = None,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteJoinSemilatticePoset:
            r"""Return the finite join-semilattice from a named poset input."""
            return self._refine_join_semilattice(
                self._raw_poset_from_named_input(
                    hasse_digraph=hasse_digraph,
                    relation_digraph=relation_digraph,
                    elements=elements,
                    relations=relations,
                    covers=covers,
                    order_predicate=order_predicate,
                    cover_predicate=cover_predicate,
                    upper_covers_dict=upper_covers_dict,
                    upper_covers=upper_covers,
                    existing=existing,
                    element_labels=element_labels,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            )

        @overload
        def LatticePoset(
            self,
            *,
            hasse_digraph: DiGraph,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset: ...

        @overload
        def LatticePoset(
            self,
            *,
            relation_digraph: DiGraph,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset: ...

        @overload
        def LatticePoset(
            self,
            *,
            elements: Iterable[PosetElement],
            relations: Iterable[tuple[PosetElement, PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset: ...

        @overload
        def LatticePoset(
            self,
            *,
            elements: Iterable[PosetElement],
            covers: Iterable[tuple[PosetElement, PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset: ...

        @overload
        def LatticePoset(
            self,
            *,
            elements: Iterable[PosetElement],
            order_predicate: Callable[[PosetElement, PosetElement], bool],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset: ...

        @overload
        def LatticePoset(
            self,
            *,
            elements: Iterable[PosetElement],
            cover_predicate: Callable[[PosetElement, PosetElement], bool],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset: ...

        @overload
        def LatticePoset(
            self,
            *,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset: ...

        @overload
        def LatticePoset(
            self,
            *,
            upper_covers: Sequence[Sequence[PosetElement]],
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset: ...

        @overload
        def LatticePoset(
            self,
            *,
            existing: _Poset,
        ) -> FiniteLatticePoset: ...

        @final
        def LatticePoset(
            self,
            *,
            hasse_digraph: DiGraph | None = None,
            relation_digraph: DiGraph | None = None,
            elements: Iterable[PosetElement] | None = None,
            relations: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            covers: Iterable[tuple[PosetElement, PosetElement]] | None = None,
            order_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            cover_predicate: Callable[[PosetElement, PosetElement], bool]
            | None = None,
            upper_covers_dict: dict[PosetElement, Sequence[PosetElement]]
            | None = None,
            upper_covers: Sequence[Sequence[PosetElement]] | None = None,
            existing: _Poset | None = None,
            element_labels: Sequence[PosetElement]
            | dict[PosetElement, PosetElement]
            | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> FiniteLatticePoset:
            r"""Return the finite lattice poset from a named poset input."""
            return self._refine_lattice(
                self._raw_poset_from_named_input(
                    hasse_digraph=hasse_digraph,
                    relation_digraph=relation_digraph,
                    elements=elements,
                    relations=relations,
                    covers=covers,
                    order_predicate=order_predicate,
                    cover_predicate=cover_predicate,
                    upper_covers_dict=upper_covers_dict,
                    upper_covers=upper_covers,
                    existing=existing,
                    element_labels=element_labels,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                )
            )
    @final
    def Constructors(self) -> Posets._Constructors:
        r"""Return the named Sage poset constructor collector."""
        return self.__class__._Constructors()

    Finite = LazyImport("category_specs.posets.subcategories.finite", "_FinitePosets")
    MeetSemilattice = LazyImport(
        "category_specs.posets.subcategories.meet_semilattice", "_MeetSemilatticePosets"
    )
    JoinSemilattice = LazyImport(
        "category_specs.posets.subcategories.join_semilattice", "_JoinSemilatticePosets"
    )
    Lattice = LazyImport(
        "category_specs.posets.subcategories.lattice", "_LatticePosets"
    )
    Subobjects = LazyImport(
        "category_specs.posets.subcategories.constructions.subobjects", "_Subobjects"
    )
    Quotients = LazyImport(
        "category_specs.posets.subcategories.constructions.quotients", "_Quotients"
    )
    Subquotients = LazyImport(
        "category_specs.posets.subcategories.constructions.subquotients",
        "_Subquotients",
    )
    ObjectsOver = LazyImport(
        "category_specs.posets.subcategories.constructions.objects_over", "_ObjectsOver"
    )
    ObjectsUnder = LazyImport(
        "category_specs.posets.subcategories.constructions.objects_under",
        "_ObjectsUnder",
    )
    CartesianProducts = LazyImport(
        "category_specs.posets.subcategories.constructions.cartesian_products",
        "_CartesianProducts",
    )
    HomCategory : TypeAlias = PosetHomCategory

    ParentMethods : TypeAlias = _PosetParentMethods
    ElementMethods : TypeAlias = _PosetElementMethods


PosetsCategory : TypeAlias = Posets
PosetsObject : TypeAlias = _PosetParentMethods
PosetsElement : TypeAlias = _PosetElementMethods
PosetsMorphism : TypeAlias = _OrderPreservingMaps
PosetsHomCategory : TypeAlias = PosetHomCategory
PosetsEndCategory : TypeAlias = PosetEndCategory
PosetsAutCategory : TypeAlias = PosetAutCategory
PosetsHom : TypeAlias = PosetHomCategory.ParentMethods
PosetsEnd : TypeAlias = PosetEndCategory.ParentMethods
PosetsAut : TypeAlias = PosetAutCategory.ParentMethods
PosetsEndomorphism : TypeAlias = PosetEndCategory.ElementMethods
PosetsAutomorphism : TypeAlias = PosetAutCategory.ElementMethods
