# ============================================================================
# VARIETY INTERFACE SPEC
#
# This file documents the intended behaviour of the Variety hierarchy via
# executable examples.  Each section uses a concrete Sage object to check
# that the abstract interface methods return mathematically correct values.
#
# ============================================================================

# ----------------------------------------------------------------------------
# 1. AFFINE PLANE CURVE: UNION OF TWO LINES (A_1 singularity)
# ----------------------------------------------------------------------------

R.<x,y> = PolynomialRing(CC, 2)
f = (x - y) * (x + y)          
# x^2 - y^2; union of lines x=y and x=-y
assert f.gradient() == vector(R, [2*x, -2*y])

X = Variety(f)                  # Construct from equation; ideal generated by f
# Interpret equations as affine equations by default.
assert X.is_affine() and not X.is_projective()
assert X.is_hypersurface()       # codimension 1 in AA^2

assert X.ambient_variety() == AA^2(CC)
assert X.is_subset_of(AA^2(CC)) and X.is_subvariety_of(AA^2(CC))

# --- Point (0,0): the node -----------------------------------------------
p = X([0, 0])                   # Affine point via coordinates
assert p.is_singular()          

X_sing = X.singular_locus()
X_sm   = X.smooth_locus()
assert p in X_sing and p not in X_sm

# X_sing is the single point {(0,0)}
assert X_sing.is_finite() and X_sing.is_closed()   
assert X_sing == Variety([x, y]) # V(x, y) = {(0,0)}; was typo '=' in original

assert X_sing.union(X_sm) == X
assert X_sing.complement() == X_sm and X_sm.complement() == X_sing
assert X - X_sing == X_sm       and X - X_sm == X_sing

assert X_sm.is_smooth()  and not X_sm.is_singular()  
assert not X_sing.is_smooth() and X_sing.is_singular()
assert not X.is_smooth()  and X.is_singular()

# --- Singularity type -------------------------------------------------------
assert p.singularity_type() == Singularity("A1")
assert p.is_node() and p.is_ordinary_double_point()
assert p.canonical_form() == Variety(x*y).point([0, 0])  # standard form uv=0
assert not p.is_cusp()

assert X.is_snc()   # Two transverse lines are simple normal crossing

f_blowup = X.blowup(p)
assert f_blowup.domain().is_smooth()

# --- Coordinate / local ring ------------------------------------------------
# The coordinate ring of X = V(x^2-y^2) is CC[x,y]/(x^2-y^2).
# CC[x,y]/(x^2-y^2) ≅ CC[x,y]/((x-y)(x+y)) ≅ CC[u] \otimes_{CC} CC[v]
assert X.coordinate_ring() == CC['x','y'].quotient(f)
assert X.coordinate_ring() == CC['x', 'y'] / f

assert p.local_ring() == X.local_ring(p)
R_local = p.local_ring()


# ----------------------------------------------------------------------------
# 2. SMOOTH LINE: SINGLE LINE x = y IN AA^2
# ----------------------------------------------------------------------------

X = Variety(x - y)
assert X.is_smooth() and X.smooth_locus() == X
assert X.singular_locus() == Variety.empty()
assert X.is_snc()

assert X.is_isomorphic_to(AA^1(CC))

# resolution() -> VarietyMorphism; for smooth X the morphism is the identity.
# normalization() -> Variety; trivially X itself for smooth X.
assert X.resolution().domain() == X   # identity map: source = X
assert X.normalization() == X


# ----------------------------------------------------------------------------
# 3. A SINGLE CLOSED POINT (0,0) IN AA^2
# ----------------------------------------------------------------------------

X = Variety([x - y, x + y])    # V(x-y, x+y) = V(x, y) = {(0,0)}
assert X.cardinality() == 1
assert AA^2(CC).point((0,0)) in X and AA^2(CC).point((1,1)) not in X

p = X.point((0,0))
R_local = p.local_ring()
# The local ring of a smooth point on a 0-dimensional variety over CC is CC.
assert R_local.is_local() and R_local.is_regular()
assert R_local.dimension() == 0 and R_local.is_field() and R_local == CC

assert X.singular_locus() == Variety.empty() and X.smooth_locus() == X
assert X.is_smooth() and X.dimension() == 0
assert X.resolution().domain() == X


# ----------------------------------------------------------------------------
# 4. A_n SINGULARITIES
# ----------------------------------------------------------------------------

# Standard form for A_n: y^2 - x^{n+1} = 0 at (0,0).

# A_2 singularity (cusp): y^2 - x^3
X = Variety(y^2 - x^3)
p = X((0,0))
assert X.is_singular() and X.singular_locus() == p
assert p.singularity_type() == Singularity("A2")
assert not p.is_node() and p.is_cusp()

# A_1 through A_10
for n in range(1, 11):
    X = Variety(y^2 - x^(n+1))   # A_n: y^2 = x^{n+1}
    p = X((0, 0))

    assert p.singularity_type() == Singularity(f"A{n}")
    assert p.milnor_number() == n

    MF = p.milnor_fibre()
    assert MF.is_connected()
    assert MF.homotopy_type() == Wedge([Sphere(1)] * n)
    assert MF.homology(0).rank() == 1
    assert MF.homology(1).rank() == n
    assert all(MF.homology(k).rank() == 0 for k in range(2, MF.dimension() + 1))

# D_n singularities: x^(n-1) + x*y^2, n >= 4
for n in range(4, 11):
    X = Variety(x^(n-1) + x*y^2)
    p = X((0, 0))

    assert X.is_singular()
    assert p.singularity_type() == Singularity(f"D{n}")
    assert p.milnor_number() == n

    MF = p.milnor_fibre()
    assert MF.is_connected()
    assert MF.homotopy_type() == Wedge([Sphere(1)] * n)
    assert MF.homology(0).rank() == 1
    assert MF.homology(1).rank() == n
    assert all(MF.homology(k).rank() == 0 for k in range(2, MF.dimension() + 1))

# Exceptional simple singularities
E_forms = {
    "E6": x^3 + y^4,
    "E7": x^3 + x*y^3,
    "E8": x^3 + y^5,
}

for name, g in E_forms.items():
    X = Variety(g)
    p = X((0, 0))
    mu = Integer(name[1:])

    assert X.is_singular()
    assert p.singularity_type() == Singularity(name)
    assert p.milnor_number() == mu

    MF = p.milnor_fibre()
    assert MF.is_connected()
    assert MF.homotopy_type() == Wedge([Sphere(1)] * mu)
    assert MF.homology(0).rank() == 1
    assert MF.homology(1).rank() == mu
    assert all(MF.homology(k).rank() == 0 for k in range(2, MF.dimension() + 1))


# ----------------------------------------------------------------------------
# 5. PROJECTIVE CURVE: UNION OF TWO LINES IN PP^2
# ----------------------------------------------------------------------------

# Working in homogeneous coordinates [X:Y:Z]
R3.<X,Y,Z> = PolynomialRing(CC, 3)

# Projective closure of (x-y)(x+y)=0 in AA^2 is (X-Y)(X+Y)=0 in PP^2.
C_aff = Curve((x - y) * (x + y))
C = C_aff.projective_closure()

assert C.ambient_space() == PP^2(CC)
assert not C.is_affine() and C.is_projective()
assert C.dimension() == 1
assert C.is_nodal() and not C.is_cuspidal()   
assert C == Variety((X - Y) * (X + Y))        # Curve ⊂ Variety hierarchy

# Degree-genus formula for plane curve of degree d: p_a = (d-1)(d-2)/2.
# For d=2: p_a = 0.  Geometric genus: p_g = p_a - #nodes = 0 (no nodes on the
# normalization; the two components are smooth P^1s).
assert C.genus() == 0              # geometric genus of normalization
assert C.geometric_genus() == 0   # p_g = h^0(K_C) = 0
assert C.arithmetic_genus() == 0  # p_a = (2-1)(2-2)/2 = 0   

assert not C.is_elliptic()    # not genus 1; 
assert not C.is_abelian_variety()

assert C.irregularity() == 0      # q = h^{0,1} = 0 (rational components)

# Plurigenus: P_n = h^0(nK_C).  K_{P^1} ~ -2H has degree -2 < 0, so
# h^0(nK) = 0 for n≥1.  P_0 = 1 by convention.
assert [C.plurigenus(n) for n in range(10)] == [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Hodge diamond for a smooth genus-0 curve (here using the normalization /
# smooth model; the singular C has the same Hodge numbers since p_g = q = 0):
#   h^{p,q}:  p\q  0  1
#              0  [ 1  0 ]
#              1  [ 0  1 ]
assert C.hodge_diamond() == Matrix(ZZ, [[1, 0], [0, 1]])

# Hilbert polynomial of a degree-d plane curve with p_a=0:
#   P(t) = d*t + (1 - p_a) = 2t + 1
t = polygen(QQ, 't')
assert C.hilbert_polynomial(t) == 2*t + 1

# Rational curves have Kodaira dimension κ = -∞
assert C.kodaira_dimension() == -Infinity

# Classification summary
assert C.is_rational()
assert not C.is_elliptic() and not C.is_calabi_yau()
assert not C.is_hyperbolic() and not C.is_general_type()


# ----------------------------------------------------------------------------
# 6. FERMAT QUARTIC SURFACE (K3)
# ----------------------------------------------------------------------------

R4.<x,y,z,w> = PolynomialRing(CC, 4)
f_quartic = x^4 + y^4 + z^4 + w^4
X = Variety(f_quartic)          # Fermat quartic surface in PP^3

assert X.degree() == 4
assert X.ambient_variety() == PP^3(CC)
assert X.is_projective() and X.is_quasi_projective()

assert X.is_k3() and X.is_calabi_yau()
assert X.is_smooth()
assert X.smooth_locus() == X and X.singular_locus() == Variety.empty()

K_X   = X.canonical_divisor()
Pic_X = X.picard_group()
assert K_X in Pic_X
# K3 surfaces have trivial canonical bundle: K_X ~ 0 in Pic(X).
# '==' here denotes linear equivalence (membership in the 0-class of Pic).
assert K_X.is_linearly_equivalent_to(Pic_X(0))
assert K_X == 0

# K3 Hodge diamond:
#   h^{p,q}: p\q  0   1   2
#             0  [ 1   0   1 ]
#             1  [ 0  20   0 ]
#             2  [ 1   0   1 ]
# h^{1,1} = 20 for ANY K3 surface (topological invariant).
assert X.hodge_diamond() == Matrix(ZZ, [[1, 0, 1], [0, 20, 0], [1, 0, 1]])

assert X.is_hypersurface()

X_PP3 = X.as_divisor()          # View quartic as a divisor in PP^3
H     = PP^3(CC).hyperplane_class()
assert X_PP3.is_linearly_equivalent_to(4 * H)

# Adjunction: K_X = (K_{PP^3} + X)|_X = (-4H + 4H)|_X = 0.
assert X.canonical_divisor() == (PP^3(CC).canonical_divisor() + X_PP3).restrict_to(X)
# K_{PP^n} = -(n+1)H; for PP^3: K = -4H.
assert PP^3(CC).canonical_divisor() == -4 * H


# ----------------------------------------------------------------------------
# 7. COBLE SURFACE AND K3 DOUBLE COVER
# ----------------------------------------------------------------------------

# --- Rational sextic --------------------------------------------------------
# A rational sextic C ⊂ PP^2 is a degree-6 curve with geometric genus 0.
# By the genus formula p_a = (6-1)(6-2)/2 = 10, so C must have 10 singularities to
# reduce p_g = p_a - #nodes = 0.
R3p.<x,y,z> = PolynomialRing(CC, 3)

# Explicit rational sextic with exactly 10 A1 nodes, obtained from the
# parametrization [t^6-t^5-t^4+t : -t^6-t^5+t^4+t^2-1 : -t^6+t^5+t^3-t^2+1]
# by eliminating t via resultant.  Verified: 10 singular points in chart z=1,
# none at infinity, each with nondegenerate Hessian (A1 type).
F = (
    137*x^6
    - 79*x^5*y - 61*x^5*z
    - 244*x^4*y^2 - 423*x^4*y*z - 134*x^4*z^2
    - 438*x^3*y^3 - 585*x^3*y^2*z - 128*x^3*y*z^2 + 19*x^3*z^3
    - 279*x^2*y^4 - 606*x^2*y^3*z - 395*x^2*y^2*z^2 - 61*x^2*y*z^3 + 7*x^2*z^4
    - 137*x*y^5 - 386*x*y^4*z - 550*x*y^3*z^2 - 479*x*y^2*z^3 - 212*x*y*z^4 - 34*x*z^5
    + 9*y^6 - 54*y^5*z - 256*y^4*z^2 - 385*y^3*z^3 - 276*y^2*z^4 - 97*y*z^5 - 13*z^6
)

C = Variety(F)
assert C.is_singular()
assert C.ambient_variety() == PP^2(CC)
assert C.degree() == 6

C_sing = C.singular_locus()
assert C_sing.cardinality() == 10
assert all(p.singularity_type() == Singularity("A1") for p in C_sing)

# --- Blowup -----------------------------------------------------------------
f = PP^2(CC).blowup(C_sing)     # f: S -> PP^2, a Blowup morphism
S = f.domain()                   # Coble surface  
assert S.is_rational()

# Picard lattice of Bl_{10} PP^2 is generated by H, E_1,...,E_{10} with
# H^2 = 1, E_i^2 = -1, H·E_i = 0, E_i·E_j = 0 (i≠j).
assert S.picard_group().as_lattice().is_isometric_to(Lattice.I(1, 10))
# NOTE: T_Co is the IMAGE in the K3 lattice, thus is twisted by 2, yielding <2> + <-2>^{10}

K_S = S.canonical_divisor()
# Defining property of Coble surfaces: no anti-canonical sections, unique
# bi-anti-canonical section (the proper transform of C).
assert (-K_S).h(0) == 0          # h^0(O_S(-K_S)) = 0: no cubic through all 10 nodes
assert (-2 * K_S).h(0) == 1      # h^0(O_S(-2K_S)) = 1: unique member of |-2K_S|

# --- Exceptional divisors ---------------------------------------------------
Eis = f.exceptional_locus()
assert Eis.cardinality() == 10

# Blowing up SMOOTH points of PP^2 gives exceptional divisors E_i ≅ PP^1
# with self-intersection E_i^2 = -1 (standard formula for surface blowup).
# E_i^2 = -2 holds for the PULLBACK of E_i to the
# K3 cover (degree-2 cover doubles the self-intersection).
assert all(Ei.self_intersection() == -1 for Ei in Eis)

assert Variety(f(Ei) for Ei in Eis) == C_sing   # images of E_i are the blown-up points
assert Variety(f.pullback(pi) for pi in C_sing) == Eis

# Pullback of hyperplane class and canonical class formula
Hp = f.pullback(PP^2(CC).hyperplane_class())
# K_{Bl_10 PP^2} = -3H + E_1 + ... + E_{10} (standard formula)
assert K_S == -3 * Hp + sum(Ei.as_divisor() for Ei in Eis)

# Proper transform of C: degree 6 curve passing through each node with mult 2
# gives the class 6H - 2*(E_1 + ... + E_{10}) = -2*K_S.
C_tilde = f.proper_transform(C)
assert C_tilde.as_divisor() == 6 * Hp - 2 * sum(Ei.as_divisor() for Ei in Eis)
assert C_tilde.as_divisor() == -2 * K_S   # Coble's defining relation

# --- K3 double cover --------------------------------------------------------
B = C_tilde   # Branch divisor: the proper transform of the rational sextic
assert B in (-2 * K_S).linear_system()
assert B.is_linearly_equivalent_to(-2 * K_S)

# Construct double cover of S branched over B.
f_k3 = VarietyMorphism.branched_double_cover(B) # Can automatically infer X from B
X    = f_k3.domain()             # K3 surface
assert X.is_k3() and f_k3.codomain() == S

# K3 Hodge diamond (same as section 6)
assert X.hodge_diamond() == Matrix(ZZ, [[1, 0, 1], [0, 20, 0], [1, 0, 1]])

# Covering involution
iota_X = f_k3.deck_transformation()
assert iota_X in X.Aut()
assert iota_X.order() == 2

assert X.quotient(iota_X) == S       # X / iota_X ≅ S (Coble surface as quotient)
assert S == X / iota_X

# Branch and ramification data (using interface method names, not spec's original names)
assert f_k3.branch_divisor() == B    
R_X = f_k3.ramification_divisor()    
assert R_X in X.picard_group()       # Ramification divisor is a Cartier divisor on X

# TODO: assert on explicit equations for a normalization
# TODO: assert on explicit equations for blowups
# TODO: construct and assert on a cycle of copies of PP^1, each intersecting the next at exactly one point
# - assert on geometric_genus(), arithmetic_genus(), number of nodes, number of irreducible components, 
# TODO: construct and assert on Dynkin type of dual complex of resolution

# TODO: test stability of curves. C := ....
# assert C.is_stable() and C.is_lci()
# omega_C = C.canonical_sheaf()
# assert omega_C^3.is_very_amply() # Powers are tensor powers, multiplication is tensor
# assert C.hilbert_polynomial("n") == (6n - 1)*(C.genus() - 1)
# assert all(p.singularity_type() == Singularity("A1") for p in C.singular_locus())
# assert C.Aut().is_finite()
## For curves: Aut is finite iff C.arithmetic_genus() != 1 and 
## assert all(C_i * C_j >= 3 for C_i in C.irreducible_components() if C_i.is_rational() and C_i.is_smooth() for C_j in C.irreducible_components()
## DM69: every non-singular rational component meets the other components in at least 3 points.
# assert C.is_semistable() # stable => semistable

# TODO: assert on semistable curves. C := ...
# assert C.is_semistable()
# assert C.Aut().is_reductive()
## assert all(C_i * C_j >= 2 for C_i in C.irreducible_components() if C_i.is_rational() and C_i.is_smooth() for C_j in C.irreducible_components()
## DM69: every non-singular rational component meets the other components in at least *2* points

# TODO: allow marking points on curves
# C = ....
# p1, p2 = C.point(...), C.point(...)
# C.mark_points([p1,p2])
# (assert on stability, semistability, etc)
# assert that elliptic curves naturally have one marked point by construction

# TODO: assert on a family of elliptic curves X := V(x^3-y^2+t)
# Central fiber == rational curve with a cusp
# General fiber == smooth elliptic curve
# Construct as a flat morphism f: X -> DD^1(CC) [the complex disc]
# assert f^(-1)(0) == f.fiber_over(0) == f.central_fiber() == f.special_fiber() 
# assert f^(-1)(t) == f.fiber_over(t) == f.general_fiber() when t is an indeterminate
# assert f^(-1)(1/2) == V(x^3-y^2+ (1/2)) 

# TODO: assert on Weierstrass family of curves
# R1.<t> = PolynomialRing(CC, 1)
# R.<x,y,z> = PolynomialRing(R1, 3)
# f(t,x,y,z) = y^2*z - x*(x-z)*(x-t*z)
# X = Variety(f).as_projective_variety()
## Allow interpreting a homogeneous equation as defining a projective variety
## (Must validate homogeneity)
# assert X == Proj(R/f)
# pi = X.as_family_over(R1) # Interpret as a family in t
# assert pi.general_fiber().is_smooth()
# assert pi^(-1)(0).is_singular() and pi^(-1)(1).is_singular()
# assert degenerate points have only one double point singularity.

