# Tests for Rings().Constructors().IntegerModRing() / .Zmod() / .Integers()
# Assertions sourced from sage.rings.finite_rings.integer_mod_ring doctests.

import sys
sys.path.insert(0, '/home/dzack/research')
from plans.category_specs.rings import Rings
from sage.all import ZZ, GF

NR = Rings().Constructors()

# ---------------------------------------------------------------------------
# IntegerModRing(n) — basic  (IntegerModRing_generic class docstring)
# ---------------------------------------------------------------------------

R12 = NR.IntegerModRing(12)
assert R12.order() == 12
assert R12.characteristic() == 12
assert R12.is_finite() is True
assert R12.is_commutative_ring() is True
assert R12.is_field() is False        # 12 is not prime
assert R12.is_integral_domain() is False  # 2 * 6 = 0

# Element arithmetic
assert R12(7) + R12(8) == R12(3)    # 15 mod 12
assert R12(5) * R12(5) == R12(1)    # 25 mod 12
assert R12(0).is_zero() is True
assert R12(1).is_one() is True

# Units: elements coprime to 12
assert R12(5).is_unit() is True
assert R12(4).is_unit() is False    # gcd(4, 12) = 4 ≠ 1
assert R12(7).is_unit() is True

# Factored order
assert dict(R12.factored_order()) == {2: 2, 3: 1}

# ---------------------------------------------------------------------------
# IntegerModRing(p) — prime modulus is a field  (docstring)
# ---------------------------------------------------------------------------

R7 = NR.IntegerModRing(7)
assert R7.is_field() is True
assert R7.characteristic() == 7
assert R7.order() == 7

# R7 as a field should match GF(7)
assert R7.is_isomorphic(GF(7))

# ---------------------------------------------------------------------------
# Zmod alias  (same constructor)
# ---------------------------------------------------------------------------

Z6 = NR.Zmod(6)
assert Z6.order() == 6
assert Z6.characteristic() == 6

# ---------------------------------------------------------------------------
# Integers alias  (same constructor)
# ---------------------------------------------------------------------------

Z5 = NR.Integers(5)
assert Z5.order() == 5
assert Z5.is_field() is True

# ---------------------------------------------------------------------------
# Modulus method  (IntegerModRing.modulus)
# ---------------------------------------------------------------------------

assert R12.modulus() == ZZ(12)

# ---------------------------------------------------------------------------
# unit_gens  (IntegerModRing_generic.unit_gens)
# ---------------------------------------------------------------------------

# Unit group of Z/12Z is Z/2Z × Z/2Z, generated by {5, 7} or similar
unit_gens = R12.unit_gens()
assert all(g.is_unit() for g in unit_gens)
assert len(unit_gens) >= 1

# ---------------------------------------------------------------------------
# multiplicative_generator  (for prime modulus = cyclic group)
# ---------------------------------------------------------------------------

gen = R7.multiplicative_generator()
assert gen.multiplicative_order() == 6

# ---------------------------------------------------------------------------
# Quotient ring via ZZ.quotient  (same objects, different constructor)
# ---------------------------------------------------------------------------

from sage.all import ZZ as SageZZ
R12_via_quotient = SageZZ.quotient(12 * SageZZ)
# The spec-constructed and Sage-native objects should be isomorphic
assert R12_via_quotient.order() == 12
