r"""Quotient modules."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, final, override

from sage.misc.abstract_method import abstract_method

from ....cat import QuotientsCategory

if TYPE_CHECKING:
    from ....types import CategoryElement, Matrix, RingElement, RModMorphism, RModule, RModuleElement, SubModule


class _Quotients(QuotientsCategory):
    r"""Quotient module category.

    Canonical chain: ``Modules(R).Quotients()``.
    """

    class ParentMethods:
        @abstract_method
        def cover(self) -> RModule:
            r"""Return the module being quotiented."""
            ...

        @abstract_method
        def relations(self) -> RModule:
            r"""Return the submodule of relations defining this quotient."""
            ...

        @final
        def ambient_module(self) -> RModule:
            r"""Return the module being quotiented."""
            return self.cover()

        @abstract_method
        def projection(self) -> RModMorphism: ...

        @final
        def quotient_map(self) -> RModMorphism:
            r"""Return the quotient projection."""
            return self.projection()

        @abstract_method
        def lift_map(self) -> RModMorphism: ...

        @abstract_method
        def lift(self, x: RModuleElement) -> RModuleElement: ...

        @abstract_method
        def free_cover(self) -> RModule: ...

        @abstract_method
        def free_relations(self) -> RModule: ...

        @abstract_method
        def retract(self, x: RModuleElement) -> RModuleElement: ...

        @abstract_method
        def cokernel_basis_indices(self) -> tuple[CategoryElement, ...]:
            r"""Return the basis indices surviving in this quotient normal form."""
            ...

        @override
        @abstract_method
        def quotient_module(self, submodule: SubModule, check: bool = True) -> RModule: ...

        @final
        def quotient_by_submodule(self, submodule: SubModule, check: bool = True) -> RModule:
            r"""Return ``M / submodule`` for a submodule ``submodule <= M``."""
            return self.quotient_module(submodule, check=check)

        @final
        def quotient_by_generators(
            self,
            generators: Sequence[RModuleElement],
            check: bool = True,
            already_echelonized: bool = False,
        ) -> RModule:
            r"""Return ``M / <generators>``, where ``<generators>`` is their generated submodule."""
            return self.quotient_module(
                self.submodule(generators, check=check, already_echelonized=already_echelonized),
                check=check,
            )

        @final
        def quotient_by_relation_matrix(
            self,
            relation_matrix: Matrix,
            check: bool = True,
            already_echelonized: bool = False,
        ) -> RModule:
            r"""Return ``M / R``, where ``R`` is the submodule spanned by the rows of ``relation_matrix``."""
            return self.quotient_module(
                self.submodule(relation_matrix, check=check, already_echelonized=already_echelonized),
                check=check,
            )

        @final
        def quotient_by_relation_rows(
            self,
            relation_rows: Sequence[Sequence[RingElement]],
            check: bool = True,
            already_echelonized: bool = False,
        ) -> RModule:
            r"""Return ``M / R``, where ``R`` is the submodule generated by ``relation_rows``."""
            return self.quotient_module(
                self.submodule(relation_rows, check=check, already_echelonized=already_echelonized),
                check=check,
            )

    class ElementMethods:
        @final
        def lift(self) -> RModuleElement:
            return self.projection().lift(self)

    class MorphismMethods: ...
