r"""Lattices over Dedekind domains.

A *lattice over a Dedekind domain* ``R`` is a finitely generated, torsion-free
``R``-module ``L`` equipped with a symmetric, nondegenerate, integral bilinear
form ``b: L \times L \to R``.

Because ``R`` is a Dedekind domain, ``L`` need not be free: it is projective
of constant rank.  The structure theorem for finitely generated modules over a
Dedekind domain guarantees ``L \cong R^{n-1} \oplus I`` for some fractional
ideal ``I``, so the rank is well-defined.

This is the tier at which the following become well-defined:

- ``signature_pair()`` — via base-change to an archimedean completion of ``K``
- ``is_primitive(S)`` — whether a submodule ``S \subseteq L`` is primitive
- ``index_in(other)`` — index ``[\text{other} : L]``
- ``overlattice(gens)`` — super-lattice generated by ``L`` and extra vectors
- ``rational_span()`` — ``L \otimes_R K`` as a bilinear module over ``K``

.. NOTE::

    ``dual_lattice()``, ``discriminant_group()``, and ``inclusion_morphism()``
    are first defined at the ``Bilinear().Integral()`` tier — they only require
    ``R`` to be an integral domain with fraction field ``K``, not a Dedekind domain.
    ``orthogonal_complement(S)`` is first defined at ``Bilinear().Symmetric()``.
    ``orthogonal_group()`` is inherited from the formed-module aut-category owner.
"""

from __future__ import annotations

from typing import final

from sage.misc.abstract_method import abstract_method

from ...cat import CategoryWithAxiom_over_base_ring
from ...types import (
    Automorphism,
    Integer,
    Lattice,
    RingElement,
    RModule,
    SetFamily,
    SignaturePair,
    SubModule,
)
from ..chain import LatticesCategory


class _LatticesOverDedekindDomain(CategoryWithAxiom_over_base_ring):
    r"""Integral bilinear modules whose base ring is a Dedekind domain.

    Canonical chain: ``Lattices(R).OverDedekindDomain()``.

    Objects: pairs ``(L, b)`` with:
    - ``L`` finitely generated and torsion-free over a Dedekind domain ``R``
    - ``b: L \times L \to R`` symmetric, nondegenerate, integral

    EXAMPLES::

        sage: L = Lattice.U()   # not tested
        sage: L in Modules(ZZ).WithForms().Bilinear().Symmetric()\
        ...     .Nondegenerate().Integral().OverDedekindDomain()   # not tested
        True
    """

    _base_category_class_and_axiom = (LatticesCategory, "OverDedekindDomain")
    _defining_predicates = ("is_over_dedekind_domain", "is_torsionfree")

    class ParentMethods:
        @final
        def is_over_dedekind_domain(self) -> bool:
            return True

        @final
        def is_torsionfree(self) -> bool:
            return True

        @abstract_method
        def rank(self) -> Integer:
            r"""Return the rank of ``L`` as an ``R``-module.

            Well-defined for torsion-free modules over a Dedekind domain
            (rank = local rank at any prime).
            """
            ...

        @abstract_method
        def is_primitive(self, S: SubModule) -> bool:
            r"""Return ``True`` iff ``S`` is a primitive submodule of ``L``:
            the quotient ``L/S`` is torsion-free.

            For lattices: ``S \subseteq L`` is primitive iff ``L/S`` is free,
            i.e. ``S = L \cap (S \otimes K)`` inside ``L \otimes K``.
            """
            ...

        @abstract_method
        def signature_pair(self) -> SignaturePair:
            r"""Return the signature ``(n_+, n_-)`` of the form over ``\mathbb{R}``.

            ``n_+`` (resp. ``n_-``) is the number of positive (resp. negative)
            eigenvalues of the Gram matrix tensored to ``\mathbb{R}``.

            EXAMPLES::

                sage: Lattice.U().signature_pair()   # not tested
                (1, 1)
                sage: Lattice.E(8).signature_pair()   # not tested
                (8, 0)
            """
            ...

        @final
        def signature(self) -> Integer:
            r"""Return the signature ``n_+ - n_-`` (the index).

            EXAMPLES::

                sage: Lattice.U().signature()   # not tested
                0
            """
            p, q = self.signature_pair()
            return p - q

        @abstract_method
        def index_in(self, other: Lattice) -> RingElement:
            r"""Return the index ``[other : self]`` assuming ``self \subseteq other``.

            For lattices this is ``|\det(G_{\mathrm{other}}) / \det(G_{\mathrm{self}})|^{1/2}``
            when the Gram matrices are compatible.
            """
            ...

        @abstract_method
        def overlattice(self, gens: SetFamily) -> Lattice:
            r"""Return the lattice spanned by ``self`` and ``gens``.

            The result is a super-lattice of ``self`` inside ``L \otimes K``;
            the form is inherited from the dual lattice.
            """
            ...

        @abstract_method
        def rational_span(self) -> RModule:
            r"""Return ``L \otimes_R K`` as a bilinear module over ``K``.

            EXAMPLES::

                sage: L = Lattice.E(8)   # not tested
                sage: L.rational_span().base_ring()   # not tested
                Rational Field
            """
            ...

    class ElementMethods:
        @abstract_method
        def reflection(self) -> Automorphism:
            r"""Return the orthogonal reflection ``s_v: w \mapsto w - \frac{2b(v,w)}{b(v,v)} v``.

            Requires ``b(v,v)`` to be a unit (or invertible) in the base ring.
            The reflection ``s_v`` is an element of ``O(L)``.
            """
            ...

    class MorphismMethods: ...
