r"""Quotient modules."""

from __future__ import annotations

from abc import abstractmethod
from collections.abc import Sequence
from typing import TYPE_CHECKING, cast, final

from ....cat import QuotientsCategory

if TYPE_CHECKING:
    from ....types import (
        CategoryElement,
        Matrix,
        RingElement,
        RModMorphism,
        RModule,
        RModuleElement,
        SubModule,
    )


class _Quotients(QuotientsCategory):
    r"""Quotient module category.

    Canonical chain: ``Modules(R).Quotients()``.
    """

    class ParentMethods:
        @abstractmethod
        def cover(self) -> RModule:
            r"""Return the module being quotiented."""
            ...

        @abstractmethod
        def relations(self) -> RModule:
            r"""Return the submodule of relations defining this quotient."""
            ...

        @abstractmethod
        def is_torsionfree(self) -> bool:
            r"""Return whether this quotient module is torsion-free."""
            ...

        @final
        def ambient_module(self) -> RModule:
            r"""Return the module being quotiented."""
            return self.cover()

        @abstractmethod
        def projection(self) -> RModMorphism: ...

        @final
        def quotient_map(self) -> RModMorphism:
            r"""Return the quotient projection."""
            return self.projection()

        @abstractmethod
        def lift_map(self) -> RModMorphism: ...

        @abstractmethod
        def lift(self, x: RModuleElement) -> RModuleElement: ...

        @abstractmethod
        def free_cover(self) -> RModule: ...

        @abstractmethod
        def free_relations(self) -> RModule: ...

        @abstractmethod
        def retract(self, x: RModuleElement) -> RModuleElement: ...

        @abstractmethod
        def cokernel_basis_indices(self) -> tuple[CategoryElement, ...]:
            r"""Return the basis indices surviving in this quotient normal form."""
            ...

        @abstractmethod
        def quotient_module(self, submodule: SubModule, check: bool = True) -> RModule: ...

        @final
        def quotient_by_submodule(self, submodule: SubModule, check: bool = True) -> RModule:
            r"""Return ``M / submodule`` for a submodule ``submodule <= M``."""
            return self.quotient_module(submodule, check=check)

        @final
        def quotient_by_generators(
            self,
            generators: Sequence[RModuleElement],
            check: bool = True,
            already_echelonized: bool = False,
        ) -> RModule:
            r"""Return ``M / <generators>`` for the generated submodule."""
            return self.quotient_module(
                cast(
                    SubModule,
                    getattr(self, "submodule")(generators, check=check, already_echelonized=already_echelonized),
                ),
                check=check,
            )

        @final
        def quotient_by_relation_matrix(
            self,
            relation_matrix: Matrix,
            check: bool = True,
            already_echelonized: bool = False,
        ) -> RModule:
            r"""Return ``M / R`` for rows of ``relation_matrix``."""
            return self.quotient_module(
                cast(
                    SubModule,
                    getattr(self, "submodule")(
                        relation_matrix,
                        check=check,
                        already_echelonized=already_echelonized,
                    ),
                ),
                check=check,
            )

        @final
        def quotient_by_relation_rows(
            self,
            relation_rows: Sequence[Sequence[RingElement]],
            check: bool = True,
            already_echelonized: bool = False,
        ) -> RModule:
            r"""Return ``M / R`` for the submodule generated by relation rows."""
            return self.quotient_module(
                cast(
                    SubModule,
                    getattr(self, "submodule")(
                        relation_rows,
                        check=check,
                        already_echelonized=already_echelonized,
                    ),
                ),
                check=check,
            )

    class ElementMethods:
        @abstractmethod
        def parent(self) -> _Quotients.ParentMethods:
            r"""Return the quotient module containing this element."""
            ...

        @final
        def lift(self) -> RModuleElement:
            return cast(RModuleElement, getattr(self.parent().projection(), "lift")(self))
