r"""Finite join-semilattice poset subcategory."""

from __future__ import annotations

from typing import TYPE_CHECKING, final

from sage.misc.abstract_method import abstract_method

from ...cat import Category
from ...cat import CategoryWithAxiom_singleton as CategoryWithAxiom
from .join_semilattice import _JoinSemilatticePosets

if TYPE_CHECKING:
    from ...types import FiniteJoinSemilatticePoset, Matrix, PosetElement


class _FiniteJoinSemilatticePosets(CategoryWithAxiom):
    r"""Finite posets in which every pair has a join."""

    _base_category_class_and_axiom = (_JoinSemilatticePosets, "Finite")

    @final
    def super_categories(self) -> list[Category]:
        from .. import Posets

        return [_JoinSemilatticePosets(), Posets().Finite()]

    class ParentMethods:
        @abstract_method
        def coatoms(self) -> list[PosetElement]:
            r"""Return the elements covered by the top element."""
            ...

        @abstract_method
        def join_matrix(self) -> Matrix:
            r"""Return the matrix of pairwise joins."""
            ...

        @abstract_method
        def subjoinsemilattice(self, elements: list[PosetElement]) -> FiniteJoinSemilatticePoset:
            r"""Return the join-subsemilattice generated by ``elements``."""
            ...

    class ElementMethods: ...
    class MorphismMethods: ...
