r"""Finite meet-semilattice poset subcategory."""

from __future__ import annotations

from typing import TYPE_CHECKING, final

from sage.misc.abstract_method import abstract_method

from ...cat import Category
from ...cat import CategoryWithAxiom_singleton as CategoryWithAxiom
from .meet_semilattice import _MeetSemilatticePosets

if TYPE_CHECKING:
    from ...types import FiniteMeetSemilatticePoset, Matrix, PosetElement


class _FiniteMeetSemilatticePosets(CategoryWithAxiom):
    r"""Finite posets in which every pair has a meet."""

    _base_category_class_and_axiom = (_MeetSemilatticePosets, "Finite")

    @final
    def super_categories(self) -> list[Category]:
        from .. import Posets

        return [_MeetSemilatticePosets(), Posets().Finite()]

    class ParentMethods:
        @abstract_method
        def atoms(self) -> list[PosetElement]:
            r"""Return the elements covering the bottom element."""
            ...

        @abstract_method
        def meet_matrix(self) -> Matrix:
            r"""Return the matrix of pairwise meets."""
            ...

        @abstract_method
        def pseudocomplement(self, element: PosetElement) -> PosetElement:
            r"""Return the meet-pseudocomplement of ``element``."""
            ...

        @abstract_method
        def submeetsemilattice(self, elements: list[PosetElement]) -> FiniteMeetSemilatticePoset:
            r"""Return the meet-subsemilattice generated by ``elements``."""
            ...

    class ElementMethods: ...
    class MorphismMethods: ...
