r"""Finite order-theoretic lattice poset subcategory."""

from __future__ import annotations

from collections.abc import Callable
from typing import TYPE_CHECKING, final

from sage.categories.finite_lattice_posets import FiniteLatticePosets as SageFiniteLatticePosets
from sage.misc.abstract_method import abstract_method

from ...cat import Category, CategoryWithAxiom_singleton as CategoryWithAxiom
from .finite_join_semilattice import _FiniteJoinSemilatticePosets
from .finite_meet_semilattice import _FiniteMeetSemilatticePosets
from .lattice import _LatticePosets

if TYPE_CHECKING:
    from ...types import FiniteLatticePoset, LatticePoset, PosetElement


class _FiniteLatticePosets(CategoryWithAxiom):
    r"""Finite lattice posets."""

    _base_category_class_and_axiom = (_LatticePosets, "Finite")

    @final
    def super_categories(self) -> list[Category]:
        return [
            _LatticePosets(),
            _FiniteMeetSemilatticePosets(),
            _FiniteJoinSemilatticePosets(),
            SageFiniteLatticePosets(),
        ]

    class ParentMethods:
        @abstract_method
        def complements(
            self,
            element: PosetElement | None = None,
        ) -> list[PosetElement] | dict[PosetElement, list[PosetElement]]:
            r"""Return complements of ``element``, or all complements by element."""
            ...

        @abstract_method
        def is_atomic(self, certificate: bool = False) -> bool:
            r"""Return whether every element is a join of atoms."""
            ...

        @abstract_method
        def is_coatomic(self, certificate: bool = False) -> bool:
            r"""Return whether every element is a meet of coatoms."""
            ...

        @abstract_method
        def is_complemented(self, certificate: bool = False) -> bool:
            r"""Return whether every element has a complement."""
            ...

        @abstract_method
        def is_distributive(self, certificate: bool = False) -> bool:
            r"""Return whether finite meets distribute over finite joins."""
            ...

        @abstract_method
        def is_modular(self, L: LatticePoset | None = None, certificate: bool = False) -> bool:
            r"""Return whether the lattice is modular."""
            ...

        @abstract_method
        def is_semidistributive(self) -> bool:
            r"""Return whether the lattice is join- and meet-semidistributive."""
            ...

        @abstract_method
        def join_irreducibles(self) -> list[PosetElement]:
            r"""Return the join-irreducible elements."""
            ...

        @abstract_method
        def join_irreducibles_poset(self) -> FiniteLatticePoset:
            r"""Return the poset of join-irreducible elements."""
            ...

        @abstract_method
        def meet_irreducibles(self) -> list[PosetElement]:
            r"""Return the meet-irreducible elements."""
            ...

        @abstract_method
        def meet_irreducibles_poset(self) -> FiniteLatticePoset:
            r"""Return the poset of meet-irreducible elements."""
            ...

        @abstract_method
        def irreducibles_poset(self) -> FiniteLatticePoset:
            r"""Return the poset of meet- and join-irreducible elements."""
            ...

        @abstract_method
        def is_lattice_morphism(self, f: Callable[[PosetElement], PosetElement], codomain: LatticePoset) -> bool:
            r"""Return whether ``f`` preserves finite meets and joins."""
            ...

        @abstract_method
        def sublattice(self, elements: list[PosetElement]) -> LatticePoset:
            r"""Return the sublattice generated by ``elements``."""
            ...

        @abstract_method
        def sublattices_lattice(self) -> LatticePoset:
            r"""Return the lattice of sublattices ordered by inclusion."""
            ...

    class ElementMethods: ...
    class MorphismMethods: ...
