"""
Task 1.1 Example 3: Construct a third independent example of a 10-nodal rational sextic curve.
"""


# This file was *autogenerated* from the file computations/task1_1_sextic_example3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_80 = Integer(80); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10)
from sage.all import *

print("=" * _sage_const_80 )
print("Task 1.1 Example 3: Rational Sextic with 10 Nodes")
print("=" * _sage_const_80 )

# ============================================================================
# Step 1: Generic Parametrization P¹ → P²
# ============================================================================
print("\n[Step 1] Defining parametrization...")

R = PolynomialRing(QQ, names=('s', 't',)); (s, t,) = R._first_ngens(2)

# Fresh parametrization
f0 = s**_sage_const_6  + _sage_const_3 *s**_sage_const_5 *t + _sage_const_2 *s**_sage_const_4 *t**_sage_const_2  - s**_sage_const_3 *t**_sage_const_3  + s**_sage_const_2 *t**_sage_const_4  + _sage_const_2 *s*t**_sage_const_5  + t**_sage_const_6 
f1 = _sage_const_2 *s**_sage_const_6  + s**_sage_const_5 *t + _sage_const_3 *s**_sage_const_4 *t**_sage_const_2  + _sage_const_2 *s**_sage_const_3 *t**_sage_const_3  - s**_sage_const_2 *t**_sage_const_4  + s*t**_sage_const_5  + _sage_const_3 *t**_sage_const_6 
f2 = s**_sage_const_6  - s**_sage_const_5 *t + s**_sage_const_4 *t**_sage_const_2  + _sage_const_3 *s**_sage_const_3 *t**_sage_const_3  + _sage_const_2 *s**_sage_const_2 *t**_sage_const_4  - s*t**_sage_const_5  + _sage_const_2 *t**_sage_const_6 

print(f"  f₀(s:t) = {f0}")
print(f"  f₁(s:t) = {f1}")
print(f"  f₂(s:t) = {f2}")

# ============================================================================
# Step 2: Implicit Equation via Resultants
# ============================================================================
print("\n[Step 2] Computing implicit equation F(x,y,z) = 0...")

R_xyz = PolynomialRing(QQ, names=('x', 'y', 'z',)); (x, y, z,) = R_xyz._first_ngens(3)
W = PolynomialRing(R_xyz, names=('s',)); (s,) = W._first_ngens(1)

# Dehomogenize (set t=1)
f0_s = f0.substitute(t=_sage_const_1 )
f1_s = f1.substitute(t=_sage_const_1 )
f2_s = f2.substitute(t=_sage_const_1 )

f0_W = W(f0_s)
f1_W = W(f1_s)
f2_W = W(f2_s)

poly1 = x * f1_W - y * f0_W
poly2 = x * f2_W - z * f0_W

print("  Computing resultant with respect to s...")
F_res = poly1.resultant(poly2)
F_res = R_xyz(F_res)

# Factor and extract the sextic component
factors = F_res.factor()
F = None
for f, mult in factors:
    if f.total_degree() == _sage_const_6 :
        F = f
        break

if F is None:
    print("  Error: Could not find sextic factor.")
    exit(_sage_const_1 )

print(f"  Final F degree: {F.total_degree()}")

# ============================================================================
# Step 3: Find All Singular Points
# ============================================================================
print("\n[Step 3] Finding singular points...")

x_gen, y_gen, z_gen = F.parent().gens()
Fx = F.derivative(x_gen)
Fy = F.derivative(y_gen)
Fz = F.derivative(z_gen)

# Work in affine chart z=1
R_xy = PolynomialRing(QQ, names=('X', 'Y',)); (X, Y,) = R_xy._first_ngens(2)

def to_affine(poly):
    result = R_xy(_sage_const_0 )
    # Correct handling of dict keys (tuple of exponents)
    d = poly.substitute(z=_sage_const_1 ).dict()
    for exponents, c in d.items():
        # exponents might be (i, j) or (i, j, 0)
        i = exponents[_sage_const_0 ]
        j = exponents[_sage_const_1 ]
        result += c * X**i * Y**j
    return result

F_aff = to_affine(F)
Fx_aff = to_affine(Fx)
Fy_aff = to_affine(Fy)

I_aff = ideal([F_aff, Fx_aff, Fy_aff])
K = QQbar

print("  Solving in chart z=1...")
sols_affine = I_aff.variety(K)

# Check for singular points at infinity (z=0)
print("  Checking points at infinity (z=0)...")
F_inf_aff = to_affine(F.substitute(z=_sage_const_0 )) # This is not really affine, it's homogeneous in x,y
# For z=0, we can check charts x=1 and y=1
# Chart x=1:
R_yz = PolynomialRing(QQ, names=('Y_inf', 'Z_inf',)); (Y_inf, Z_inf,) = R_yz._first_ngens(2)
F_x1 = F.substitute(x=_sage_const_1 )
Fx_x1 = Fx.substitute(x=_sage_const_1 )
Fy_x1 = Fy.substitute(x=_sage_const_1 )
Fz_x1 = Fz.substitute(x=_sage_const_1 )
I_x1 = ideal([F_x1.substitute(z=_sage_const_0 ), Fx_x1.substitute(z=_sage_const_0 ), Fy_x1.substitute(z=_sage_const_0 ), Fz_x1.substitute(z=_sage_const_0 )])
sols_x1 = []
try:
    sols_x1 = I_x1.variety(K)
except: pass

all_singular_points = []
for sol in sols_affine:
    all_singular_points.append((sol[X], sol[Y], K(_sage_const_1 )))
for sol in sols_x1:
    all_singular_points.append((K(_sage_const_1 ), sol[Y_inf], K(_sage_const_0 )))

# De-duplicate points (by projective equivalence)
def normalize(pt):
    for c in pt:
        if c != _sage_const_0 :
            return tuple(x/c for x in pt)
    return pt

unique_points = []
for pt in all_singular_points:
    npt = normalize(pt)
    is_new = True
    for upt in unique_points:
        if all(abs(npt[i] - upt[i]) < _sage_const_1en9  for i in range(_sage_const_3 )):
            is_new = False
            break
    if is_new:
        unique_points.append(npt)

print(f"  Total unique singular points (projective): {len(unique_points)}")

# ============================================================================
# Step 4: Verify Nodes using Hessian Rank
# ============================================================================
print("\n[Step 4] Verifying nodes (A₁ singularities)...")

def is_node_at_point(poly, pt):
    # Hessian matrix at pt
    vars = [x_gen, y_gen, z_gen]
    H = matrix(K, _sage_const_3 , _sage_const_3 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            val = poly.derivative(vars[i], vars[j]).substitute(x=pt[_sage_const_0 ], y=pt[_sage_const_1 ], z=pt[_sage_const_2 ])
            H[i,j] = val
    return H.rank() == _sage_const_2 

nodes = []
for idx, pt in enumerate(unique_points):
    if is_node_at_point(F, pt):
        nodes.append(pt)
        print(f"    Point {idx+_sage_const_1 }: ✓ NODE (A₁)")
    else:
        print(f"    Point {idx+_sage_const_1 }: ✗ NOT A NODE")

print(f"\n  Found {len(nodes)} nodes.")

# ============================================================================
# Step 5: Stabilizer Group Computation
# ============================================================================
print("\n" + "=" * _sage_const_80 )
print("Step 5: Compute Stabilizer Group Γ_Co")
print("=" * _sage_const_80 )

# Lattice definitions as in Example 2
T_En_gram = diagonal_matrix(ZZ, [_sage_const_2 , _sage_const_2 ] + [-_sage_const_2 ]*_sage_const_8 )
h_Co = vector(ZZ, [_sage_const_1 ] + [_sage_const_0 ]*_sage_const_9 )
theta = diagonal_matrix(ZZ, [_sage_const_1 , _sage_const_1 ] + [-_sage_const_1 ]*_sage_const_8 )

def reflection_matrix(r, G):
    n = G.nrows()
    r_norm = int(r * G * r)
    s_r = matrix(QQ, n, n)
    Gr = G * r
    for i in range(n):
        for j in range(n):
            s_r[i,j] = (_sage_const_1  if i == j else _sage_const_0 ) - QQ(_sage_const_2  * r[i] * Gr[j]) / r_norm
    return s_r.change_ring(ZZ)

# Roots to check: standard basis vectors
roots = []
for i in range(_sage_const_10 ):
    v = vector(ZZ, [_sage_const_0 ]*_sage_const_10 ); v[i] = _sage_const_1 ; roots.append(v)

gamma_gens = []
for r in roots:
    try:
        s_r = reflection_matrix(r, T_En_gram)
        # Check if s_r preserves the lattice
        if s_r.transpose() * T_En_gram * s_r == T_En_gram:
            # Check if s_r preserves polarization and commutes with involution
            if (s_r * h_Co == h_Co) and (s_r * theta == theta * s_r):
                if s_r not in gamma_gens:
                    gamma_gens.append(s_r)
    except Exception as e:
        pass

print(f"Found {len(gamma_gens)} reflection generators in Γ_Co.")

# ============================================================================
# Step 6: Save Results
# ============================================================================
results_file = 'computations/task1_1_example3_results.txt'
with open(results_file, 'w') as f:
    f.write("Task 1.1 Example 3: 10-nodal Rational Sextic Curve\n")
    f.write("=" * _sage_const_80  + "\n\n")
    f.write("1. Parametrization f_i(s,t):\n")
    f.write(f"   f0 = {f0}\n")
    f.write(f"   f1 = {f1}\n")
    f.write(f"   f2 = {f2}\n\n")
    f.write(f"2. Implicit Equation F(x,y,z) degree: {F.total_degree()}\n")
    f.write(f"3. Singular Points:\n")
    f.write(f"   Total found: {len(unique_points)}\n")
    f.write(f"   Nodes (A1): {len(nodes)}\n\n")
    f.write("4. Node Positions (Projective):\n")
    for idx, pt in enumerate(nodes):
        f.write(f"   p_{idx+_sage_const_1 } = [{pt[_sage_const_0 ]} : {pt[_sage_const_1 ]} : {pt[_sage_const_2 ]}]\n")
    f.write("\n5. Stabilizer Group Γ_Co Analysis:\n")
    f.write(f"   Lattice T_En Gram Matrix: diag(2, 2, -2, ..., -2)\n")
    f.write(f"   Polarization h_Co: {list(h_Co)}\n")
    f.write(f"   Involution theta: diag(1, 1, -1, ..., -1)\n")
    f.write(f"   Number of reflection generators: {len(gamma_gens)}\n")

print(f"\nResults saved to {results_file}")

