r"""One-object subcategory for callable-backed enumerated sets."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from sage.categories.category_singleton import Category_singleton
from sage.misc.abstract_method import abstract_method

if TYPE_CHECKING:
    from ...types import Cardinality, SetElement


from .. import Sets


class _EnumeratedSetsFromIterator(Category_singleton):
    r"""Enumerated set generated by a callable returning a fresh iterator."""

    def super_categories(self) -> list:
        return [Sets().Countable()]

    class ParentMethods:
        @abstract_method
        def __contains__(self, x: Any) -> bool: ...

        @abstract_method
        def __iter__(self): ...

        @abstract_method
        def cardinality(self) -> Cardinality: ...

        @abstract_method
        def an_element(self) -> SetElement: ...

        @abstract_method
        def unrank(self, i: int) -> SetElement: ...

        @abstract_method
        def _element_constructor_(self, el: SetElement) -> SetElement: ...

        @abstract_method
        def clear_cache(self) -> None: ...
