r"""One-object subcategory for callable-backed enumerated sets."""

from __future__ import annotations

from collections.abc import Iterator
from typing import TYPE_CHECKING, Any, final

from sage.categories.category_singleton import Category_singleton
from sage.misc.abstract_method import abstract_method

if TYPE_CHECKING:
    from ...types import Cardinality, SetElement


from .. import Sets
from ...cat import Category


class _EnumeratedSetsFromIterator(Category_singleton):
    r"""Enumerated set generated by a callable returning a fresh iterator."""

    @final
    def super_categories(self) -> list[Category]:
        return [Sets().Countable()]

    class ParentMethods:
        @abstract_method
        def __contains__(self, x: Any) -> bool: ...

        @abstract_method
        def __iter__(self) -> Iterator[SetElement]: ...

        @abstract_method
        def cardinality(self) -> Cardinality: ...

        @abstract_method
        def an_element(self) -> SetElement: ...

        @abstract_method
        def _element_constructor_(self, el: SetElement) -> SetElement: ...

        @abstract_method
        def clear_cache(self) -> None: ...

    class ElementMethods: ...
    class MorphismMethods: ...
