r"""Order-theoretic poset category surface.

Subcategory hierarchy::

    Posets()
    |-- Finite()
    |-- Lattice()
    |   `-- Finite()
    `-- HomCategory()
        |-- EndCategory()
        `-- AutCategory()

The root category specifies sets equipped with a partial order. Lattice posets
are order-theoretic meet/join lattices, not module lattices.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import TYPE_CHECKING, Any, final

from sage.categories.posets import Posets as SagePosets
from sage.misc.abstract_method import abstract_method
from sage.misc.cachefunc import cached_method
from sage.misc.lazy_import import LazyImport

from ..cat import Cat, Category
from ..sets import Sets
from .homsets import PosetAutCategory, PosetEndCategory, PosetHomCategory

if TYPE_CHECKING:
    from ..types import PosetElement, PosetSubset


class _PosetParentMethods:
    r"""Methods on partially ordered sets."""

    @abstract_method
    def le(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x <= y`` in this poset."""
        ...

    @final
    def lt(self, x: PosetElement, y: PosetElement) -> bool:
        return self.le(x, y) and x != y

    @final
    def ge(self, x: PosetElement, y: PosetElement) -> bool:
        return self.le(y, x)

    @final
    def gt(self, x: PosetElement, y: PosetElement) -> bool:
        return self.lt(y, x)

    @abstract_method(optional=True)
    def upper_covers(self, x: PosetElement) -> list[PosetElement]:
        r"""Return the elements covering ``x`` from above."""
        ...

    @abstract_method(optional=True)
    def lower_covers(self, x: PosetElement) -> list[PosetElement]:
        r"""Return the elements covered by ``x``."""
        ...

    @abstract_method(optional=True)
    def order_ideal(self, elements: Iterable[PosetElement]) -> PosetSubset:
        r"""Return the lower set generated by ``elements``."""
        ...

    @abstract_method(optional=True)
    def order_filter(self, elements: Iterable[PosetElement]) -> PosetSubset:
        r"""Return the upper set generated by ``elements``."""
        ...

    @abstract_method
    def directed_subset(self, elements: Iterable[PosetElement], direction: str) -> PosetSubset:
        r"""Return the order ideal or order filter generated by ``elements``."""
        ...

    @abstract_method
    def principal_order_ideal(self, x: PosetElement) -> PosetSubset:
        r"""Return the principal lower set generated by ``x``."""
        ...

    @abstract_method
    def principal_order_filter(self, x: PosetElement) -> PosetSubset:
        r"""Return the principal upper set generated by ``x``."""
        ...

    @abstract_method
    def order_ideal_toggle(self, ideal: PosetSubset, x: PosetElement) -> PosetSubset:
        r"""Toggle ``x`` in the distributive lattice of order ideals."""
        ...

    @abstract_method
    def order_ideal_toggles(
        self,
        ideal: PosetSubset,
        elements: Iterable[PosetElement],
    ) -> PosetSubset:
        r"""Apply order-ideal toggles in sequence."""
        ...

    @abstract_method
    def is_order_ideal(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an order ideal."""
        ...

    @abstract_method
    def is_order_filter(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an order filter."""
        ...

    @abstract_method
    def is_chain_of_poset(self, subset: Iterable[PosetElement], ordered: bool = False) -> bool:
        r"""Return whether ``subset`` is a chain."""
        ...

    @abstract_method
    def is_antichain_of_poset(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an antichain."""
        ...


class _PosetElementMethods:
    r"""Methods on elements of non-facade posets."""

    @abstract_method
    def __le__(self, other: PosetElement) -> bool: ...

    @abstract_method
    def __lt__(self, other: PosetElement) -> bool: ...

    @abstract_method
    def __ge__(self, other: PosetElement) -> bool: ...

    @abstract_method
    def __gt__(self, other: PosetElement) -> bool: ...


class _PosetMorphismMethods:
    r"""Order-preserving maps between posets."""

    @abstract_method
    def is_order_preserving(self) -> bool: ...


class Posets(Category):
    r"""Category of sets equipped with a partial order."""

    @final
    def _sage_super_categories(self) -> tuple[Category, ...]:
        return (SagePosets(),)

    @final
    def super_categories(self) -> list[Category]:
        return [Sets(), SagePosets()]

    class SubcategoryMethods:
        @cached_method
        @final
        def Finite(self) -> Category:
            return self._with_axiom("Finite")

        @cached_method
        @final
        def Lattice(self) -> Category:
            from .subcategories.lattice import _LatticePosets

            return _LatticePosets()

    class Constructors:
        r"""Poset constructors.

        Concrete constructor methods are admitted after the Sage poset constructor
        inventory is decided.
        """

    _Constructors = Constructors

    @cached_method
    @final
    def Constructors(self):
        return self.__class__._Constructors()

    Finite = LazyImport("category_specs.posets.subcategories.finite", "_FinitePosets")
    Lattice = LazyImport("category_specs.posets.subcategories.lattice", "_LatticePosets")
    Subobjects = LazyImport("category_specs.posets.subcategories.constructions.subobjects", "_Subobjects")
    Quotients = LazyImport("category_specs.posets.subcategories.constructions.quotients", "_Quotients")
    Subquotients = LazyImport("category_specs.posets.subcategories.constructions.subquotients", "_Subquotients")
    ObjectsOver = LazyImport("category_specs.posets.subcategories.constructions.objects_over", "_ObjectsOver")
    ObjectsUnder = LazyImport("category_specs.posets.subcategories.constructions.objects_under", "_ObjectsUnder")
    CartesianProducts = LazyImport(
        "category_specs.posets.subcategories.constructions.cartesian_products",
        "_CartesianProducts",
    )
    HomCategory = PosetHomCategory

    ParentMethods = _PosetParentMethods
    ElementMethods = _PosetElementMethods
    MorphismMethods = _PosetMorphismMethods


PosetsCategory = Posets
PosetsObject = Posets.ParentMethods
PosetsElement = Posets.ElementMethods
PosetsMorphism = Posets.MorphismMethods
PosetsHomCategory = PosetHomCategory
PosetsEndCategory = PosetEndCategory
PosetsAutCategory = PosetAutCategory
PosetsHom = PosetHomCategory.ParentMethods
PosetsEnd = PosetEndCategory.ParentMethods
PosetsAut = PosetAutCategory.ParentMethods
PosetsEndomorphism = PosetEndCategory.ElementMethods
PosetsAutomorphism = PosetAutCategory.ElementMethods
