r"""Order-theoretic poset category surface.

Subcategory hierarchy::

    Posets()
    |-- Finite()
    |-- MeetSemilattice()
    |   `-- Finite()
    |-- JoinSemilattice()
    |   `-- Finite()
    |-- Lattice()
    |   `-- Finite()
    `-- HomCategory()
        |-- EndCategory()
        `-- AutCategory()

The root category specifies sets equipped with a partial order. Lattice posets
are order-theoretic meet/join lattices, not module lattices.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Sequence
from typing import TYPE_CHECKING, Any, final, override

from sage.categories.posets import Posets as SagePosets
from sage.misc.abstract_method import abstract_method
from sage.misc.cachefunc import cached_method
from sage.misc.lazy_import import LazyImport

from ..cat import Cat, Category
from ..sets import Sets
from ..utils import refine_category
from .homsets import PosetAutCategory, PosetEndCategory, PosetHomCategory

if TYPE_CHECKING:
    from ..types import (
        DiGraph,
        FiniteJoinSemilatticePoset,
        FiniteLatticePoset,
        FiniteMeetSemilatticePoset,
        Poset,
        PosetElement,
        PosetSubset,
        SageFinitePoset,
    )


class _PosetParentMethods:
    r"""Methods on partially ordered sets."""

    @override
    @abstract_method
    def le(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x <= y`` in this poset."""
        ...

    @override
    @final
    def lt(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x < y`` in this poset."""
        return self.le(x, y) and x != y

    @override
    @final
    def ge(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x >= y`` in this poset."""
        return self.le(y, x)

    @override
    @final
    def gt(self, x: PosetElement, y: PosetElement) -> bool:
        r"""Return whether ``x > y`` in this poset."""
        return self.lt(y, x)

    @override
    @abstract_method(optional=True)
    def upper_covers(self, x: PosetElement) -> list[PosetElement]:
        r"""Return the elements covering ``x`` from above."""
        ...

    @override
    @abstract_method(optional=True)
    def lower_covers(self, x: PosetElement) -> list[PosetElement]:
        r"""Return the elements covered by ``x``."""
        ...

    @override
    @abstract_method(optional=True)
    def order_ideal(self, elements: Iterable[PosetElement]) -> PosetSubset:
        r"""Return the lower set generated by ``elements``."""
        ...

    @override
    @abstract_method(optional=True)
    def order_filter(self, elements: Iterable[PosetElement]) -> PosetSubset:
        r"""Return the upper set generated by ``elements``."""
        ...

    @override
    @abstract_method
    def directed_subset(self, elements: Iterable[PosetElement], direction: str) -> PosetSubset:
        r"""Return the order ideal or order filter generated by ``elements``."""
        ...

    @override
    @abstract_method
    def principal_order_ideal(self, x: PosetElement) -> PosetSubset:
        r"""Return the principal lower set generated by ``x``."""
        ...

    @override
    @abstract_method
    def principal_order_filter(self, x: PosetElement) -> PosetSubset:
        r"""Return the principal upper set generated by ``x``."""
        ...

    @override
    @abstract_method
    def order_ideal_toggle(self, ideal: PosetSubset, x: PosetElement) -> PosetSubset:
        r"""Toggle ``x`` in the distributive lattice of order ideals."""
        ...

    @override
    @abstract_method
    def order_ideal_toggles(
        self,
        ideal: PosetSubset,
        elements: Iterable[PosetElement],
    ) -> PosetSubset:
        r"""Apply order-ideal toggles in sequence."""
        ...

    @override
    @abstract_method
    def is_order_ideal(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an order ideal."""
        ...

    @override
    @abstract_method
    def is_order_filter(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an order filter."""
        ...

    @override
    @abstract_method
    def is_chain_of_poset(self, subset: Iterable[PosetElement], ordered: bool = False) -> bool:
        r"""Return whether ``subset`` is a chain."""
        ...

    @override
    @abstract_method
    def is_antichain_of_poset(self, subset: Iterable[PosetElement]) -> bool:
        r"""Return whether ``subset`` is an antichain."""
        ...


class _PosetElementMethods:
    r"""Methods on elements of non-facade posets."""

    @abstract_method
    def __le__(self, other: PosetElement) -> bool:
        r"""Return whether this element is less than or equal to ``other``."""
        ...

    @abstract_method
    def __lt__(self, other: PosetElement) -> bool:
        r"""Return whether this element is strictly less than ``other``."""
        ...

    @abstract_method
    def __ge__(self, other: PosetElement) -> bool:
        r"""Return whether this element is greater than or equal to ``other``."""
        ...

    @abstract_method
    def __gt__(self, other: PosetElement) -> bool:
        r"""Return whether this element is strictly greater than ``other``."""
        ...


class _PosetMorphismMethods:
    r"""Order-preserving maps between posets."""

    @abstract_method
    def is_order_preserving(self) -> bool:
        r"""Return whether this morphism preserves the partial order."""
        ...


class Posets(Category):
    r"""Category of sets equipped with a partial order.

    Canonical chain: ``Posets()``.
    """

    @override
    @final
    def _sage_super_categories(self) -> tuple[Category, ...]:
        return (SagePosets(),)

    @override
    @final
    def super_categories(self) -> list[Category]:
        r"""Return sets and Sage posets as supercategories."""
        return [Sets(), SagePosets()]

    class SubcategoryMethods:
        @cached_method
        @final
        def Finite(self) -> Category:
            r"""Return the finite-poset subcategory."""
            return self._with_axiom("Finite")

        @cached_method
        @final
        def MeetSemilattice(self) -> Category:
            r"""Return the meet-semilattice subcategory of posets."""
            from .subcategories.meet_semilattice import _MeetSemilatticePosets

            return _MeetSemilatticePosets()

        @cached_method
        @final
        def JoinSemilattice(self) -> Category:
            r"""Return the join-semilattice subcategory of posets."""
            from .subcategories.join_semilattice import _JoinSemilatticePosets

            return _JoinSemilatticePosets()

        @cached_method
        @final
        def Lattice(self) -> Category:
            r"""Return the order-theoretic lattice subcategory of posets."""
            from .subcategories.lattice import _LatticePosets

            return _LatticePosets()

    class Constructors:
        r"""Poset constructors.

        The acyclic ``DiGraph`` constructor is canonical. Other methods are
        named adaptations of Sage's documented finite ``Poset(...)`` input
        cases.
        """

        @final
        def _raw_poset(
            self,
            data: Any,
            *,
            element_labels: Sequence[PosetElement] | dict[PosetElement, PosetElement] | None = None,
            cover_relations: bool = False,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> SageFinitePoset:
            from sage.combinat.posets.posets import Poset as SagePoset

            return SagePoset(
                data,
                element_labels=element_labels,
                cover_relations=cover_relations,
                linear_extension=linear_extension,
                facade=facade,
                key=key,
            )

        @final
        def _refine_constructed_poset(self, poset: SageFinitePoset, categories: Sequence[Category]) -> Poset:
            return refine_category(poset, [Posets(), Posets().Finite(), *categories])

        @final
        def _refine_meet_semilattice(self, poset: SageFinitePoset) -> FiniteMeetSemilatticePoset:
            from sage.combinat.posets.lattices import MeetSemilattice as SageMeetSemilattice

            assert poset.is_meet_semilattice(), "constructed poset is not a meet-semilattice"
            return self._refine_constructed_poset(
                SageMeetSemilattice(poset, check=False),
                [Posets().MeetSemilattice().Finite()],
            )

        @final
        def _refine_join_semilattice(self, poset: SageFinitePoset) -> FiniteJoinSemilatticePoset:
            from sage.combinat.posets.lattices import JoinSemilattice as SageJoinSemilattice

            assert poset.is_join_semilattice(), "constructed poset is not a join-semilattice"
            return self._refine_constructed_poset(
                SageJoinSemilattice(poset, check=False),
                [Posets().JoinSemilattice().Finite()],
            )

        @final
        def _refine_lattice(self, poset: SageFinitePoset) -> FiniteLatticePoset:
            from sage.combinat.posets.lattices import LatticePoset as SageLatticePoset

            assert poset.is_meet_semilattice(), "constructed poset is not a meet-semilattice"
            assert poset.is_join_semilattice(), "constructed poset is not a join-semilattice"
            return self._refine_constructed_poset(
                SageLatticePoset(poset, check=False),
                [Posets().Lattice().Finite()],
            )

        @final
        def poset_from_digraph(
            self,
            digraph: DiGraph,
            *,
            cover_relations: bool = False,
            element_labels: Sequence[PosetElement] | dict[PosetElement, PosetElement] | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> Poset:
            r"""Return the finite poset represented by ``digraph``."""
            return self._refine_constructed_poset(
                self._raw_poset(
                    digraph,
                    element_labels=element_labels,
                    cover_relations=cover_relations,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                ),
                [],
            )

        @final
        def poset_from_relations(
            self,
            elements: Iterable[PosetElement],
            relations: Iterable[tuple[PosetElement, PosetElement]],
            *,
            cover_relations: bool = False,
            element_labels: Sequence[PosetElement] | dict[PosetElement, PosetElement] | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> Poset:
            r"""Return the finite poset generated by ``relations`` on ``elements``."""
            return self._refine_constructed_poset(
                self._raw_poset(
                    (elements, relations),
                    element_labels=element_labels,
                    cover_relations=cover_relations,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                ),
                [],
            )

        @final
        def poset_from_order_predicate(
            self,
            elements: Iterable[PosetElement],
            le: Callable[[PosetElement, PosetElement], bool],
            *,
            element_labels: Sequence[PosetElement] | dict[PosetElement, PosetElement] | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> Poset:
            r"""Return the finite poset whose order relation is ``le``."""
            return self._refine_constructed_poset(
                self._raw_poset(
                    (elements, le),
                    element_labels=element_labels,
                    cover_relations=False,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                ),
                [],
            )

        @final
        def poset_from_cover_predicate(
            self,
            elements: Iterable[PosetElement],
            covers: Callable[[PosetElement, PosetElement], bool],
            *,
            element_labels: Sequence[PosetElement] | dict[PosetElement, PosetElement] | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> Poset:
            r"""Return the finite poset whose cover relation is ``covers``."""
            return self._refine_constructed_poset(
                self._raw_poset(
                    (elements, covers),
                    element_labels=element_labels,
                    cover_relations=True,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                ),
                [],
            )

        @final
        def poset_from_upper_covers_dict(
            self,
            upper_covers: dict[PosetElement, Sequence[PosetElement]],
            *,
            element_labels: Sequence[PosetElement] | dict[PosetElement, PosetElement] | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> Poset:
            r"""Return the finite poset encoded by an upper-cover dictionary."""
            return self._refine_constructed_poset(
                self._raw_poset(
                    upper_covers,
                    element_labels=element_labels,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                ),
                [],
            )

        @final
        def poset_from_upper_covers(
            self,
            upper_covers: Sequence[Sequence[PosetElement]],
            *,
            element_labels: Sequence[PosetElement] | dict[PosetElement, PosetElement] | None = None,
            linear_extension: bool = False,
            facade: bool | None = None,
            key: Callable[[PosetElement], Any] | None = None,
        ) -> Poset:
            r"""Return the finite poset encoded by an ordered upper-cover list."""
            return self._refine_constructed_poset(
                self._raw_poset(
                    upper_covers,
                    element_labels=element_labels,
                    linear_extension=linear_extension,
                    facade=facade,
                    key=key,
                ),
                [],
            )

        @final
        def poset_from_existing(self, poset: Poset) -> Poset:
            r"""Return ``poset`` refined into the project finite-poset category."""
            return self._refine_constructed_poset(self._raw_poset(poset), [])

        @final
        def meet_semilattice_from_digraph(
            self,
            digraph: DiGraph,
            *,
            cover_relations: bool = False,
        ) -> FiniteMeetSemilatticePoset:
            r"""Return the finite meet-semilattice represented by ``digraph``."""
            return self._refine_meet_semilattice(self._raw_poset(digraph, cover_relations=cover_relations))

        @final
        def meet_semilattice_from_relations(
            self,
            elements: Iterable[PosetElement],
            relations: Iterable[tuple[PosetElement, PosetElement]],
            *,
            cover_relations: bool = False,
        ) -> FiniteMeetSemilatticePoset:
            r"""Return the finite meet-semilattice generated by ``relations``."""
            return self._refine_meet_semilattice(
                self._raw_poset((elements, relations), cover_relations=cover_relations)
            )

        @final
        def meet_semilattice_from_order_predicate(
            self,
            elements: Iterable[PosetElement],
            le: Callable[[PosetElement, PosetElement], bool],
        ) -> FiniteMeetSemilatticePoset:
            r"""Return the finite meet-semilattice whose order relation is ``le``."""
            return self._refine_meet_semilattice(self._raw_poset((elements, le)))

        @final
        def meet_semilattice_from_cover_predicate(
            self,
            elements: Iterable[PosetElement],
            covers: Callable[[PosetElement, PosetElement], bool],
        ) -> FiniteMeetSemilatticePoset:
            r"""Return the finite meet-semilattice whose cover relation is ``covers``."""
            return self._refine_meet_semilattice(self._raw_poset((elements, covers), cover_relations=True))

        @final
        def meet_semilattice_from_upper_covers_dict(
            self,
            upper_covers: dict[PosetElement, Sequence[PosetElement]],
        ) -> FiniteMeetSemilatticePoset:
            r"""Return the finite meet-semilattice encoded by an upper-cover dictionary."""
            return self._refine_meet_semilattice(self._raw_poset(upper_covers))

        @final
        def meet_semilattice_from_upper_covers(
            self,
            upper_covers: Sequence[Sequence[PosetElement]],
        ) -> FiniteMeetSemilatticePoset:
            r"""Return the finite meet-semilattice encoded by an upper-cover list."""
            return self._refine_meet_semilattice(self._raw_poset(upper_covers))

        @final
        def meet_semilattice_from_existing(self, poset: Poset) -> FiniteMeetSemilatticePoset:
            r"""Return ``poset`` refined as a finite meet-semilattice."""
            return self._refine_meet_semilattice(self._raw_poset(poset))

        @final
        def join_semilattice_from_digraph(
            self,
            digraph: DiGraph,
            *,
            cover_relations: bool = False,
        ) -> FiniteJoinSemilatticePoset:
            r"""Return the finite join-semilattice represented by ``digraph``."""
            return self._refine_join_semilattice(self._raw_poset(digraph, cover_relations=cover_relations))

        @final
        def join_semilattice_from_relations(
            self,
            elements: Iterable[PosetElement],
            relations: Iterable[tuple[PosetElement, PosetElement]],
            *,
            cover_relations: bool = False,
        ) -> FiniteJoinSemilatticePoset:
            r"""Return the finite join-semilattice generated by ``relations``."""
            return self._refine_join_semilattice(
                self._raw_poset((elements, relations), cover_relations=cover_relations)
            )

        @final
        def join_semilattice_from_order_predicate(
            self,
            elements: Iterable[PosetElement],
            le: Callable[[PosetElement, PosetElement], bool],
        ) -> FiniteJoinSemilatticePoset:
            r"""Return the finite join-semilattice whose order relation is ``le``."""
            return self._refine_join_semilattice(self._raw_poset((elements, le)))

        @final
        def join_semilattice_from_cover_predicate(
            self,
            elements: Iterable[PosetElement],
            covers: Callable[[PosetElement, PosetElement], bool],
        ) -> FiniteJoinSemilatticePoset:
            r"""Return the finite join-semilattice whose cover relation is ``covers``."""
            return self._refine_join_semilattice(self._raw_poset((elements, covers), cover_relations=True))

        @final
        def join_semilattice_from_upper_covers_dict(
            self,
            upper_covers: dict[PosetElement, Sequence[PosetElement]],
        ) -> FiniteJoinSemilatticePoset:
            r"""Return the finite join-semilattice encoded by an upper-cover dictionary."""
            return self._refine_join_semilattice(self._raw_poset(upper_covers))

        @final
        def join_semilattice_from_upper_covers(
            self,
            upper_covers: Sequence[Sequence[PosetElement]],
        ) -> FiniteJoinSemilatticePoset:
            r"""Return the finite join-semilattice encoded by an upper-cover list."""
            return self._refine_join_semilattice(self._raw_poset(upper_covers))

        @final
        def join_semilattice_from_existing(self, poset: Poset) -> FiniteJoinSemilatticePoset:
            r"""Return ``poset`` refined as a finite join-semilattice."""
            return self._refine_join_semilattice(self._raw_poset(poset))

        @final
        def lattice_from_digraph(self, digraph: DiGraph, *, cover_relations: bool = False) -> FiniteLatticePoset:
            r"""Return the finite lattice represented by ``digraph``."""
            return self._refine_lattice(self._raw_poset(digraph, cover_relations=cover_relations))

        @final
        def lattice_from_relations(
            self,
            elements: Iterable[PosetElement],
            relations: Iterable[tuple[PosetElement, PosetElement]],
            *,
            cover_relations: bool = False,
        ) -> FiniteLatticePoset:
            r"""Return the finite lattice generated by ``relations``."""
            return self._refine_lattice(self._raw_poset((elements, relations), cover_relations=cover_relations))

        @final
        def lattice_from_order_predicate(
            self,
            elements: Iterable[PosetElement],
            le: Callable[[PosetElement, PosetElement], bool],
        ) -> FiniteLatticePoset:
            r"""Return the finite lattice whose order relation is ``le``."""
            return self._refine_lattice(self._raw_poset((elements, le)))

        @final
        def lattice_from_cover_predicate(
            self,
            elements: Iterable[PosetElement],
            covers: Callable[[PosetElement, PosetElement], bool],
        ) -> FiniteLatticePoset:
            r"""Return the finite lattice whose cover relation is ``covers``."""
            return self._refine_lattice(self._raw_poset((elements, covers), cover_relations=True))

        @final
        def lattice_from_upper_covers_dict(
            self,
            upper_covers: dict[PosetElement, Sequence[PosetElement]],
        ) -> FiniteLatticePoset:
            r"""Return the finite lattice encoded by an upper-cover dictionary."""
            return self._refine_lattice(self._raw_poset(upper_covers))

        @final
        def lattice_from_upper_covers(
            self,
            upper_covers: Sequence[Sequence[PosetElement]],
        ) -> FiniteLatticePoset:
            r"""Return the finite lattice encoded by an upper-cover list."""
            return self._refine_lattice(self._raw_poset(upper_covers))

        @final
        def lattice_from_existing(self, poset: Poset) -> FiniteLatticePoset:
            r"""Return ``poset`` refined as a finite lattice."""
            return self._refine_lattice(self._raw_poset(poset))

    _Constructors = Constructors

    @cached_method
    @final
    def Constructors(self):
        r"""Return the named Sage poset constructor collector."""
        return self.__class__._Constructors()

    Finite = LazyImport("category_specs.posets.subcategories.finite", "_FinitePosets")
    MeetSemilattice = LazyImport("category_specs.posets.subcategories.meet_semilattice", "_MeetSemilatticePosets")
    JoinSemilattice = LazyImport("category_specs.posets.subcategories.join_semilattice", "_JoinSemilatticePosets")
    Lattice = LazyImport("category_specs.posets.subcategories.lattice", "_LatticePosets")
    Subobjects = LazyImport("category_specs.posets.subcategories.constructions.subobjects", "_Subobjects")
    Quotients = LazyImport("category_specs.posets.subcategories.constructions.quotients", "_Quotients")
    Subquotients = LazyImport("category_specs.posets.subcategories.constructions.subquotients", "_Subquotients")
    ObjectsOver = LazyImport("category_specs.posets.subcategories.constructions.objects_over", "_ObjectsOver")
    ObjectsUnder = LazyImport("category_specs.posets.subcategories.constructions.objects_under", "_ObjectsUnder")
    CartesianProducts = LazyImport(
        "category_specs.posets.subcategories.constructions.cartesian_products",
        "_CartesianProducts",
    )
    HomCategory = PosetHomCategory

    ParentMethods = _PosetParentMethods
    ElementMethods = _PosetElementMethods
    MorphismMethods = _PosetMorphismMethods


PosetsCategory = Posets
PosetsObject = Posets.ParentMethods
PosetsElement = Posets.ElementMethods
PosetsMorphism = Posets.MorphismMethods
PosetsHomCategory = PosetHomCategory
PosetsEndCategory = PosetEndCategory
PosetsAutCategory = PosetAutCategory
PosetsHom = PosetHomCategory.ParentMethods
PosetsEnd = PosetEndCategory.ParentMethods
PosetsAut = PosetAutCategory.ParentMethods
PosetsEndomorphism = PosetEndCategory.ElementMethods
PosetsAutomorphism = PosetAutCategory.ElementMethods
