r"""Mathematical-fact obligations for the algebra category subtree.

Each statement instantiates an object through the algebra DSL and asserts a real
mathematical value it must recover (a subalgebra dimension, an ideal dimension, a free
algebra's generator count / generator labels / generator presentation). A statement
passes only when the backend computes the value; it is red while the backend is
incomplete. No statement asserts category-graph structure (category membership
`obj in Cat()`, subcategory placement `.is_subcategory(...)`, axiom-owner class identity
`Algebras.Commutative is _CommutativeAlgebras`, type-package aliases
`X is Y.ElementMethods`, or abstract-method ownership `abstract_method_has_name(...)`) —
that is a property of the spec *source*, enforced by the validators in
`category_specs/validators/` (super_categories_validator, banned_spec_patterns,
constructor_name_inventory_validator). The ~31 meta-assertions that previously dominated
this file — Cat() membership, is_subcategory, class-identity, method-existence, and the
constructor-route statements that asserted only `obj in <Category>` rather than a
computed value — were removed here; migrating any structural invariant they encoded into
validator coverage is the separate "framework tests -> validators" workstream (tracked,
not silently dropped).

All retained facts are elementary computed values (matrix-algebra dimensions over QQ,
free-algebra generator data) and carry no literature citation.
"""

import sys
from pathlib import Path

THIS_FILE = Path(__file__).resolve()
sys.path.insert(0, str(THIS_FILE.parent.parent.parent))

from category_specs.algebras import Algebras
from category_specs.sets import Sets
from category_specs.utils import assert_category_statements
from sage.all import MatrixSpace, QQ, ZZ


def A():
    return Algebras(ZZ)


def AQ():
    return Algebras(QQ)


def diagonal_matrix_subalgebra():
    M2 = MatrixSpace(QQ, 2)
    e00 = M2([[1, 0], [0, 0]])
    return M2.subalgebra([e00])


def matrix_space_split_ideals_route_to_sage_sides():
    M2 = MatrixSpace(QQ, 2)
    e00 = M2([[1, 0], [0, 0]])
    methods = AQ().ParentMethods
    assert methods.left_ideal(M2, [e00]).dimension() == 2
    assert methods.right_ideal(M2, [e00]).dimension() == 2
    assert methods.two_sided_ideal(M2, [e00]).dimension() == 4
    return True


def matrix_space_principal_split_ideals_route_to_sage_sides():
    M2 = MatrixSpace(QQ, 2)
    e00 = M2([[1, 0], [0, 0]])
    methods = AQ().ParentMethods
    assert methods.principal_left_ideal(M2, e00).dimension() == 2
    assert methods.principal_right_ideal(M2, e00).dimension() == 2
    assert methods.principal_two_sided_ideal(M2, e00).dimension() == 4
    return True


def FreeAlgebra_generator_presentation():
    # UNSURE: _category_specs_generator_set / _category_specs_generator_presentation are
    # backend bookkeeping fields, not a classical algebra invariant; kept (not deleted)
    # because the presentation pairs each input label with the corresponding free-algebra
    # generator, a concrete computed correspondence. See report.
    generators = Sets().Constructors().FiniteEnumeratedSet(["x", "y"])
    algebra = A().Constructors().FreeAlgebra(generators=generators)
    return (
        algebra._category_specs_generator_set is generators
        and algebra._category_specs_generator_presentation
        == tuple(zip(tuple(generators), algebra.gens(), strict=True))
    )


def FreeAlgebra_recovers_sage_named_shapes():
    constructors = A().Constructors()
    by_names = constructors.FreeAlgebra(generator_names=("a", "b"), degrees=1)
    by_names_and_count = constructors.FreeAlgebra(
        generator_names=("u", "v"), generator_count=2
    )
    by_count_and_names = constructors.FreeAlgebra(generator_count=2, names=("p", "q"))
    by_count_and_name = constructors.FreeAlgebra(generator_count=2, name="z")
    return (
        by_names.ngens() == 2
        and tuple(str(generator) for generator in by_names.gens()) == ("a", "b")
        and by_names_and_count.ngens() == 2
        and by_count_and_names.ngens() == 2
        and tuple(str(generator) for generator in by_count_and_names.gens())
        == ("p", "q")
        and by_count_and_name.ngens() == 2
    )


CATEGORY_STATEMENTS = (
    (
        "MatrixSpace(QQ, 2).subalgebra([e00]) is the two-dimensional algebra generated by 1 and e00",
        lambda _: diagonal_matrix_subalgebra().dimension() == 2,
    ),
    (
        "split ideals of e00 in MatrixSpace(QQ, 2) have dimensions left=2, right=2, two-sided=4",
        lambda _: matrix_space_split_ideals_route_to_sage_sides(),
    ),
    (
        "principal split ideals of e00 in MatrixSpace(QQ, 2) have dimensions left=2, right=2, two-sided=4",
        lambda _: matrix_space_principal_split_ideals_route_to_sage_sides(),
    ),
    (
        "FreeAlgebra(generators={x, y}) pairs each label with its generator in the recorded presentation",  # UNSURE
        lambda _: FreeAlgebra_generator_presentation(),
    ),
    (
        "FreeAlgebra(...) recovers Sage name/count shapes: 2 generators with labels (a,b) and (p,q)",
        lambda _: FreeAlgebra_recovers_sage_named_shapes(),
    ),
)

assert_category_statements(CATEGORY_STATEMENTS)
