"""Static algebra category surface for the category spec redesign.

Subcategory hierarchy::

    Algebras(R)
    |-- Commutative()
    |-- WithBasis()
    |   `-- FiniteDimensional()
    |-- FiniteDimensional()
    |-- Semisimple()
    |-- Subobjects()
    |-- Quotients()
    |-- Subquotients()
    |-- ObjectsOver()
    |-- ObjectsUnder()
    |-- Ideals(A)
    |-- CartesianProducts()
    |-- TensorProducts()
    |-- DualObjects()
    `-- HomCategory()
        |-- EndCategory()
        `-- AutCategory()
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, final, override

from sage.categories.algebras import Algebras as SageAlgebras
from sage.misc.abstract_method import abstract_method
from sage.misc.cachefunc import cached_method
from sage.misc.lazy_import import LazyImport

from ..cat import Cat, Category, Category_module
from ..modules import Modules
from ..utils import refine_category
from .homsets import AlgebraAutCategory, AlgebraEndCategory, AlgebraHomCategory
from .subcategories.constructions.cartesian_products import _CartesianProducts
from .subcategories.constructions.dual_objects import _DualObjects
from .subcategories.constructions.ideals import _Ideals
from .subcategories.constructions.objects_over import _ObjectsOver
from .subcategories.constructions.objects_under import _ObjectsUnder
from .subcategories.constructions.quotients import _Quotients
from .subcategories.constructions.subobjects import _Subobjects
from .subcategories.constructions.subquotients import _Subquotients
from .subcategories.constructions.tensor_products import _TensorProducts

if TYPE_CHECKING:
    from ..types import (
        AdditiveGroup,
        AdditiveMonoid,
        AdditiveSemigroup,
        Algebra,
        AlgebraElement,
        AlgebraIdeal,
        Group,
        HochschildChainComplex,
        Magma,
        Monoid,
        RAlgebra,
        Ring,
        RModule,
        Semigroup,
        Set,
        SetFamily,
        Tensor,
    )


class _AlgebraParentMethods:
    @abstract_method
    def base_ring(self) -> Ring:
        r"""Return the scalar ring over which this algebra is defined."""
        ...

    @abstract_method
    def change_ring(self, R: Ring) -> Algebra:
        r"""Return the scalar extension or base change of this algebra to ``R``."""
        ...

    @abstract_method
    def algebra_generators(self) -> SetFamily:
        r"""Return algebra generators for this algebra as an ``R``-algebra."""
        ...

    @abstract_method
    def center(self) -> Algebra:
        r"""Return the center of this algebra."""
        ...

    @abstract_method
    def radical(self) -> AlgebraIdeal:
        r"""Return the Jacobson radical of this algebra."""
        ...

    @abstract_method
    def subalgebra(
        self,
        generators: Sequence[AlgebraElement],
    ) -> Algebra:
        r"""Return the subalgebra generated by ``generators``."""
        ...

    @abstract_method
    def left_ideal(self, generators: Sequence[AlgebraElement]) -> AlgebraIdeal:
        r"""Return the left ideal generated by ``generators``."""
        ...

    @abstract_method
    def right_ideal(self, generators: Sequence[AlgebraElement]) -> AlgebraIdeal:
        r"""Return the right ideal generated by ``generators``."""
        ...

    @abstract_method
    def two_sided_ideal(self, generators: Sequence[AlgebraElement]) -> AlgebraIdeal:
        r"""Return the two-sided ideal generated by ``generators``."""
        ...

    @abstract_method
    def principal_left_ideal(self, generator: AlgebraElement) -> AlgebraIdeal:
        r"""Return the left ideal generated by ``generator``."""
        ...

    @abstract_method
    def principal_right_ideal(self, generator: AlgebraElement) -> AlgebraIdeal:
        r"""Return the right ideal generated by ``generator``."""
        ...

    @abstract_method
    def principal_two_sided_ideal(self, generator: AlgebraElement) -> AlgebraIdeal:
        r"""Return the two-sided ideal generated by ``generator``."""
        ...

    @abstract_method
    def derivations(self) -> RModule:
        r"""Return the module of derivations of this algebra."""
        ...

    @abstract_method
    def annihilator(self, elements: Iterable[AlgebraElement]) -> AlgebraIdeal:
        r"""Return the ideal annihilating every element in ``elements``."""
        ...

    @final
    def ideals(self) -> Category:
        r"""Return the ideal construction category owned by this algebra."""
        return self.category().Ideals(self)

    @abstract_method
    def hochschild_complex(self, coefficients: RModule) -> HochschildChainComplex:
        r"""Return the Hochschild chain complex with coefficients in ``coefficients``."""
        ...

    @override
    @abstract_method
    def has_standard_involution(self) -> bool:
        r"""Return whether this algebra has Sage's standard involution."""
        ...

    @abstract_method
    def idempotent_lift(self, x: AlgebraElement) -> AlgebraElement:
        r"""Lift the idempotent ``x`` along the algebra's radical quotient."""
        ...

    @abstract_method
    def peirce_decomposition(
        self,
        idempotents: Sequence[AlgebraElement] | None = None,
        check: bool = True,
    ) -> Sequence[Sequence[Algebra]]:
        r"""Return the Peirce decomposition determined by ``idempotents``."""
        ...

    @abstract_method
    def semisimple_quotient(self) -> Algebra:
        r"""Return the quotient of this algebra by its Jacobson radical."""
        ...


class _AlgebraElementMethods:
    r"""Methods on elements of algebras."""

    @abstract_method
    def __mul__(self, other: AlgebraElement) -> AlgebraElement:
        r"""Return the algebra product of this element with ``other``."""
        ...


class _AlgebraMorphismMethods:
    r"""Methods on algebra morphisms."""


class Algebras(Category_module):
    r"""Category of algebras over a fixed base ring.

    Canonical chain: ``Algebras(R)``.
    """

    @override
    @final
    def _sage_super_categories(self) -> tuple[Category, ...]:
        return (SageAlgebras(self.base_ring()),)

    @override
    @final
    def _repr_object_names(self) -> str:
        return f"algebras over {self.base_ring()}"

    @override
    @final
    def super_categories(self) -> list[Category]:
        r"""Return rings-under-``R``, modules over ``R``, and Sage algebras."""
        from ..rings import Rings

        R = self.base_ring()
        return [
            Rings().RingsUnder(R),
            Modules(R),
            SageAlgebras(R),
        ]

    ParentMethods = _AlgebraParentMethods
    ElementMethods = _AlgebraElementMethods
    MorphismMethods = _AlgebraMorphismMethods
    HomCategory = AlgebraHomCategory

    class SubcategoryMethods:
        @cached_method
        @final
        def Commutative(self) -> Category:
            r"""Return the subcategory of commutative algebras."""
            return self._with_axiom("Commutative")

        @cached_method
        @final
        def WithBasis(self) -> Category:
            r"""Return the subcategory of algebras with a distinguished basis."""
            return self._with_axiom("WithBasis")

        @cached_method
        @final
        def FiniteDimensional(self) -> Category:
            r"""Return the subcategory of finite-dimensional algebras."""
            return self._with_axiom("FiniteDimensional")

        @cached_method
        @final
        def Semisimple(self) -> Category:
            r"""Return the subcategory of semisimple algebras."""
            return self._with_axiom("Semisimple")

        @cached_method
        @final
        def TensorProducts(self) -> Category:
            r"""Return the tensor-product construction category of algebras."""
            return _TensorProducts.category_of(self)

        @cached_method
        @final
        def DualObjects(self) -> Category:
            r"""Return the dual-object construction category of algebras."""
            return _DualObjects.category_of(self)

        @final
        def Ideals(self, algebra: Algebra) -> Category:
            r"""Return the category of ideals in ``algebra``."""
            assert algebra in self, f"Ideals expects an algebra in {self}: {algebra}"
            return _Ideals(algebra)

    class Constructors:
        r"""Algebra constructors over a fixed base ring.

        These constructors name the free functors from specific source
        categories into the corresponding category of ``R``-algebra objects.
        Sage's generic ``S.algebra(R)`` compatibility method is not the public
        project API.
        """

        def __init__(self, category: RAlgebra) -> None:
            self._category = category

        @final
        def category(self) -> RAlgebra:
            r"""Return the algebra category whose constructors this object names."""
            return self._category

        @final
        def base_ring(self) -> Ring:
            r"""Return the base ring of the constructed algebras."""
            return self.category().base_ring()

        @final
        def _refine_constructed_algebra(self, algebra: Algebra, categories: Sequence[Category]) -> Algebra:
            return refine_category(algebra, [self.category(), *categories])

        @final
        def _sage_algebra_from_source(
            self,
            source: Magma | Semigroup | Monoid | Group | AdditiveSemigroup | AdditiveMonoid | AdditiveGroup,
            source_category: Category,
        ) -> Algebra:
            assert source in source_category, f"Expected source in {source_category}: {source}"
            algebra = source.algebra(self.base_ring(), category=source_category)
            return self._refine_constructed_algebra(algebra, [self.category().WithBasis()])

        @final
        def free_algebra_from_set(self, generators: Set) -> Algebra:
            r"""Return the free associative unital ``R``-algebra on ``generators``."""
            from sage.algebras.free_algebra import FreeAlgebra

            assert generators.is_finite(), "free_algebra_from_set currently requires a finite generator set"
            algebra = FreeAlgebra(self.base_ring(), generators.cardinality(), "x")
            return self._refine_constructed_algebra(algebra, [self.category().WithBasis()])

        @final
        def free_algebra_from_magma(self, magma: Magma) -> Algebra:
            r"""Return the free ``R``-algebra object generated by ``magma``."""
            from sage.categories.magmas import Magmas

            assert magma in Magmas(), f"Expected a magma source: {magma}"
            assert False, (
                "Sage's magma-algebra route constructs a magmatic algebra, but "
                "category_specs has no magmatic/nonassociative algebra target yet"
            )

        @final
        def free_algebra_from_semigroup(self, semigroup: Semigroup) -> Algebra:
            r"""Return the free ``R``-algebra object generated by ``semigroup``."""
            from sage.categories.semigroups import Semigroups

            assert semigroup in Semigroups(), f"Expected a semigroup source: {semigroup}"
            assert False, (
                "Sage's semigroup-algebra route constructs an associative algebra "
                "that need not be unital; category_specs has no nonunital "
                "associative-algebra target yet"
            )

        @final
        def free_algebra_from_monoid(self, monoid: Monoid) -> Algebra:
            r"""Return the monoid algebra over ``R``."""
            from sage.categories.monoids import Monoids

            return self._sage_algebra_from_source(monoid, Monoids())

        @final
        def free_algebra_from_group(self, group: Group) -> Algebra:
            r"""Return the group algebra over ``R``."""
            from sage.categories.groups import Groups

            return self._sage_algebra_from_source(group, Groups())

        @final
        def free_algebra_from_additive_semigroup(self, semigroup: AdditiveSemigroup) -> Algebra:
            r"""Return the ``R``-algebra induced by the additive semigroup law."""
            from sage.categories.additive_semigroups import AdditiveSemigroups

            assert semigroup in AdditiveSemigroups(), f"Expected an additive semigroup source: {semigroup}"
            assert False, (
                "Sage's additive-semigroup algebra route constructs an associative "
                "algebra that need not be unital; category_specs has no nonunital "
                "associative-algebra target yet"
            )

        @final
        def free_algebra_from_additive_monoid(self, monoid: AdditiveMonoid) -> Algebra:
            r"""Return the ``R``-algebra induced by the additive monoid law."""
            from sage.categories.additive_monoids import AdditiveMonoids

            return self._sage_algebra_from_source(monoid, AdditiveMonoids())

        @final
        def free_algebra_from_additive_group(self, group: AdditiveGroup) -> Algebra:
            r"""Return the ``R``-algebra induced by the additive group law."""
            from sage.categories.additive_groups import AdditiveGroups

            return self._sage_algebra_from_source(group, AdditiveGroups())

        @final
        def from_multiplication_tensor(self, multiplication: Tensor) -> Algebra:
            r"""Return the algebra whose product is encoded by ``multiplication``.

            The tensor must lie in ``T_R(M)[1, 2]``. Its parent determines the
            underlying module ``M``, the base ring ``R``, and the preferred
            generating set used for coordinates; no separate basis, table, list
            of matrices, module-element matrix, or right-multiplication data
            belongs in this constructor surface.
            """
            assert multiplication.tensor_type() == (1, 2), (
                f"Algebra multiplication tensors must have type (1, 2): {multiplication.tensor_type()}"
            )
            base_module = multiplication.base_module()
            assert base_module.base_ring() is self.base_ring(), (
                f"Multiplication tensor must be over {self.base_ring()}: {base_module.base_ring()}"
            )
            assert False, (
                "from_multiplication_tensor needs a public tensor structure-constant "
                "extraction surface and a Sage-backed finite-rank algebra parent "
                "constructor from a base module plus a (1, 2) tensor"
            )

    _Constructors = Constructors

    @cached_method
    @final
    def Constructors(self):
        r"""Return the named algebra constructor collector over this base ring."""
        return self.__class__._Constructors(self)

    Commutative = LazyImport("category_specs.algebras.subcategories.commutative", "_CommutativeAlgebras")
    WithBasis = LazyImport("category_specs.algebras.subcategories.with_basis", "_AlgebrasWithBasis")
    FiniteDimensional = LazyImport(
        "category_specs.algebras.subcategories.finite_dimensional",
        "_FiniteDimensionalAlgebras",
    )
    Semisimple = LazyImport("category_specs.algebras.subcategories.semisimple", "_SemisimpleAlgebras")

    Subobjects = _Subobjects
    Quotients = _Quotients
    Subquotients = _Subquotients
    ObjectsOver = _ObjectsOver
    ObjectsUnder = _ObjectsUnder
    Ideals = _Ideals
    CartesianProducts = _CartesianProducts
    TensorProducts = _TensorProducts
    DualObjects = _DualObjects


AlgebrasCategory = Algebras
AlgebrasObject = Algebras.ParentMethods
AlgebrasElement = Algebras.ElementMethods
AlgebrasMorphism = Algebras.MorphismMethods
AlgebrasHomCategory = AlgebraHomCategory
AlgebrasEndCategory = AlgebraEndCategory
AlgebrasAutCategory = AlgebraAutCategory
AlgebrasHom = AlgebraHomCategory.ParentMethods
AlgebrasEnd = AlgebraEndCategory.ParentMethods
AlgebrasAut = AlgebraAutCategory.ParentMethods
AlgebrasEndomorphism = AlgebraEndCategory.ElementMethods
AlgebrasAutomorphism = AlgebraAutCategory.ElementMethods
